In [ ]:
import numpy as np
import pandas as pd
import os
from random import seed
from data_splitter import split_dataframe, concat_from_manifest
  
seed(1121)

In [ ]:
CHUNKS_DIR = "../Data"
MANIFEST   = f"{CHUNKS_DIR}/Dataset_manifest.txt"

In [11]:
data_path = '../Data/training_setA'
patient_path = os.path.join(data_path,"training")

In [3]:
patient_id = sorted(os.listdir(os.path.join(data_path,"training")))

In [ ]:
len_train = round(0.7*len(patient_id))+1
len_val = round(0.15*len(patient_id))
len_test = round(0.15*len(patient_id))
len_train + len_val + len_test == len(patient_id)

AA
AA
AA
AA
AA

In [5]:
len_train

14236

In [7]:
import random
train_id = random.sample(patient_id, len_train)
val_id = random.sample(sorted(set(patient_id) - set(train_id)), len_val)
test_id = set(patient_id) - set(train_id) - set(val_id)

## raw split

In [8]:
data_train = data_path + '/raw/training/'
data_val = data_path + '/raw/validation/'
data_test = data_path + '/raw/test/'

In [9]:
os.makedirs(data_train,exist_ok=True)
os.makedirs(data_val,exist_ok=True)
os.makedirs(data_test,exist_ok=True)

In [12]:
for p in train_id:
    df = pd.read_csv(patient_path + '/' + p, sep = "|")
    df.to_csv(data_train  + p, sep='|', index = False)

In [13]:
for p in val_id:
    df = pd.read_csv(patient_path + '/' + p, sep = "|")
    df.to_csv(data_val + p, sep='|', index = False)

In [14]:
for p in test_id:
    df = pd.read_csv(patient_path + '/' + p, sep = "|")
    df.to_csv(data_test + p, sep='|', index = False)

## Baseline

In [15]:
# function to fill missing values
def impute_missing_vals(df, attributes):

    """
    function that imputes missing values.
    
    @param df: dataframe that has missing values to be
               imputed
           attributes: list of String, attributes of dataframe
    @return df_clean: dataframe without missing values

    """
    
    """
    fill missing values by the closest values first
    ffill to fill missing values in the tail
    bfill to fill missing values in the head
    """
    # copy df
    df_clean = df.copy()
    for att in attributes:
        if df_clean[att].isnull().sum() == len(df_clean):
            df_clean[att] = df_clean[att].fillna(0)
        elif df_clean[att].isnull().sum() == len(df_clean) - 1:
            df_clean[att] = df_clean[att].ffill().bfill()
        else:
            df_clean[att] = df_clean[att].interpolate(method='nearest', limit_direction='both')
            df_clean[att] = df_clean[att].ffill().bfill()
    
    return df_clean

In [ ]:
# impute missing values and create clean dfs for all patients
for p in patient_id:
    
    # read in patient data
    df = pd.read_csv(patient_path + '/' + p, sep = "|")
    attributes = df.columns[:-1]
    
    # impute missing values
    df_clean = impute_missing_vals(df, attributes)
    
    # drop unit1 and unit2 with half missing values
    # because these two features have few information
    # drop EtCO2 with all missing values
    df_clean = df_clean.drop(['Unit1', 'Unit2', 'EtCO2'], axis=1)
    
    # save new patient data
    if p in train_id:
        save_path = data_path + '/baseline/train_baseline/'
        os.makedirs(save_path,exist_ok=True)
        df_clean.to_csv(save_path + p, sep='|', index = False)        
    
    elif p in val_id:
        save_path = data_path + '/baseline/val_baseline/'
        os.makedirs(save_path,exist_ok=True)
        df_clean.to_csv(save_path + p, sep='|', index = False)        
    
    else:
        
        save_path = data_path + '/baseline/test_baseline/'
        os.makedirs(save_path,exist_ok=True)
        df_clean.to_csv(save_path + p, sep='|', index = False)
    
    print(p)

p000001.psv
p000002.psv
p000003.psv
p000004.psv
p000005.psv
p000006.psv
p000007.psv
p000008.psv
p000009.psv
p000010.psv
p000011.psv
p000012.psv
p000013.psv
p000014.psv
p000015.psv
p000016.psv
p000017.psv
p000018.psv
p000019.psv
p000020.psv
p000021.psv
p000022.psv
p000023.psv
p000024.psv
p000025.psv
p000026.psv
p000027.psv
p000028.psv
p000029.psv
p000030.psv
p000031.psv
p000032.psv
p000033.psv
p000034.psv
p000035.psv
p000036.psv
p000037.psv
p000038.psv
p000039.psv
p000040.psv
p000041.psv
p000042.psv
p000043.psv
p000044.psv
p000045.psv
p000046.psv
p000047.psv
p000048.psv
p000049.psv
p000050.psv
p000051.psv
p000052.psv
p000053.psv
p000054.psv
p000055.psv
p000056.psv
p000057.psv
p000058.psv
p000059.psv
p000060.psv
p000061.psv
p000062.psv
p000063.psv
p000064.psv
p000065.psv
p000066.psv
p000067.psv
p000068.psv
p000069.psv
p000070.psv
p000071.psv
p000072.psv
p000073.psv
p000074.psv
p000075.psv
p000076.psv
p000077.psv
p000078.psv
p000079.psv
p000080.psv
p000081.psv
p000082.psv
p000083.psv
p000084.psv
p000085.psv
p000086.psv
p000087.psv
p000088.psv
p000089.psv
p000090.psv
p000091.psv
p000092.psv
p000093.psv
p000094.psv
p000095.psv
p000096.psv
p000097.psv
p000098.psv
p000099.psv
p000100.psv
p000101.psv
p000102.psv
p000103.psv
p000104.psv
p000105.psv
p000106.psv
p000107.psv
p000108.psv
p000109.psv
p000110.psv
p000111.psv
p000112.psv
p000113.psv
p000114.psv
p000115.psv
p000116.psv
p000117.psv
p000118.psv
p000119.psv
p000120.psv
p000121.psv
p000122.psv
p000123.psv
p000124.psv
p000125.psv
p000126.psv
p000127.psv
p000128.psv
p000129.psv
p000130.psv
p000131.psv
p000132.psv
p000133.psv
p000134.psv
p000135.psv
p000136.psv
p000137.psv
p000138.psv
p000139.psv
p000140.psv
p000141.psv
p000142.psv
p000143.psv
p000144.psv
p000145.psv
p000146.psv
p000147.psv
p000148.psv
p000149.psv
p000150.psv
p000151.psv
p000152.psv
p000153.psv
p000154.psv
p000155.psv
p000156.psv
p000157.psv
p000158.psv
p000159.psv
p000160.psv
p000161.psv
p000162.psv
p000163.psv
p000164.psv
p000165.psv
p000166.psv
p000167.psv
p000168.psv
p000169.psv
p000170.psv
p000171.psv
p000172.psv
p000173.psv
p000174.psv
p000175.psv
p000176.psv
p000177.psv
p000178.psv
p000179.psv
p000180.psv
p000181.psv
p000182.psv
p000183.psv
p000184.psv
p000185.psv
p000186.psv
p000187.psv
p000188.psv
p000189.psv
p000190.psv
p000191.psv
p000192.psv
p000193.psv
p000194.psv
p000195.psv
p000196.psv
p000197.psv
p000198.psv
p000199.psv
p000200.psv
p000201.psv
p000202.psv
p000203.psv
p000204.psv
p000205.psv
p000206.psv
p000207.psv
p000208.psv
p000209.psv
p000210.psv
p000211.psv
p000212.psv
p000213.psv
p000214.psv
p000215.psv
p000216.psv
p000217.psv
p000218.psv
p000219.psv
p000220.psv
p000221.psv
p000222.psv
p000223.psv
p000224.psv
p000225.psv
p000226.psv
p000227.psv
p000228.psv
p000229.psv
p000230.psv
p000231.psv
p000232.psv
p000233.psv
p000234.psv
p000235.psv
p000236.psv
p000237.psv
p000238.psv
p000239.psv
p000240.psv
p000241.psv
p000242.psv
p000243.psv
p000244.psv
p000245.psv
p000246.psv
p000247.psv
p000248.psv
p000249.psv
p000250.psv
p000251.psv
p000252.psv
p000253.psv
p000254.psv
p000255.psv
p000256.psv
p000257.psv
p000258.psv
p000259.psv
p000260.psv
p000261.psv
p000262.psv
p000263.psv
p000264.psv
p000265.psv
p000266.psv
p000267.psv
p000268.psv
p000269.psv
p000270.psv
p000271.psv
p000272.psv
p000273.psv
p000274.psv
p000275.psv
p000276.psv
p000277.psv
p000278.psv
p000279.psv
p000280.psv
p000281.psv
p000282.psv
p000283.psv
p000284.psv
p000285.psv
p000286.psv
p000287.psv
p000288.psv
p000289.psv
p000290.psv
p000291.psv
p000292.psv
p000293.psv
p000294.psv
p000295.psv
p000296.psv
p000297.psv
p000298.psv
p000299.psv
p000300.psv
p000301.psv
p000302.psv
p000303.psv
p000304.psv
p000305.psv
p000306.psv
p000307.psv
p000308.psv
p000309.psv
p000310.psv
p000311.psv
p000312.psv
p000313.psv
p000314.psv
p000315.psv
p000316.psv
p000317.psv
p000318.psv
p000319.psv
p000320.psv
p000321.psv
p000322.psv
p000323.psv
p000324.psv
p000325.psv
p000326.psv
p000327.psv
p000328.psv
p000329.psv
p000330.psv
p000331.psv
p000332.psv
p000333.psv
p000334.psv
p000335.psv
p000336.psv
p000337.psv
p000338.psv
p000339.psv
p000340.psv
p000341.psv
p000342.psv
p000343.psv
p000344.psv
p000345.psv
p000346.psv
p000347.psv
p000348.psv
p000349.psv
p000350.psv
p000351.psv
p000352.psv
p000353.psv
p000354.psv
p000355.psv
p000356.psv
p000357.psv
p000358.psv
p000359.psv
p000360.psv
p000361.psv
p000362.psv
p000363.psv
p000364.psv
p000365.psv
p000366.psv
p000367.psv
p000368.psv
p000369.psv
p000370.psv
p000371.psv
p000372.psv
p000373.psv
p000374.psv
p000375.psv
p000376.psv
p000377.psv
p000378.psv
p000379.psv
p000380.psv
p000381.psv
p000382.psv
p000383.psv
p000384.psv
p000385.psv
p000386.psv
p000387.psv
p000388.psv
p000389.psv
p000390.psv
p000391.psv
p000392.psv
p000393.psv
p000394.psv
p000395.psv
p000396.psv
p000397.psv
p000398.psv
p000399.psv
p000400.psv
p000401.psv
p000402.psv
p000403.psv
p000404.psv
p000405.psv
p000406.psv
p000407.psv
p000408.psv
p000409.psv
p000410.psv
p000411.psv
p000412.psv
p000413.psv
p000414.psv
p000415.psv
p000416.psv
p000417.psv
p000418.psv
p000419.psv
p000420.psv
p000421.psv
p000422.psv
p000423.psv
p000424.psv
p000425.psv
p000426.psv
p000427.psv
p000428.psv
p000429.psv
p000430.psv
p000431.psv
p000432.psv
p000433.psv
p000434.psv
p000435.psv
p000436.psv
p000437.psv
p000438.psv
p000439.psv
p000440.psv
p000441.psv
p000442.psv
p000443.psv
p000444.psv
p000445.psv
p000446.psv
p000447.psv
p000448.psv
p000449.psv
p000450.psv
p000451.psv
p000452.psv
p000453.psv
p000454.psv
p000455.psv
p000456.psv
p000457.psv
p000458.psv
p000459.psv
p000460.psv
p000461.psv
p000462.psv
p000463.psv
p000464.psv
p000465.psv
p000466.psv
p000467.psv
p000468.psv
p000469.psv
p000470.psv
p000471.psv
p000472.psv
p000473.psv
p000474.psv
p000475.psv
p000476.psv
p000477.psv
p000478.psv
p000479.psv
p000480.psv
p000481.psv
p000482.psv
p000483.psv
p000484.psv
p000485.psv
p000486.psv
p000487.psv
p000488.psv
p000489.psv
p000490.psv
p000491.psv
p000492.psv
p000493.psv
p000494.psv
p000495.psv
p000496.psv
p000497.psv
p000498.psv
p000499.psv
p000500.psv
p000501.psv
p000502.psv
p000503.psv
p000504.psv
p000505.psv
p000506.psv
p000507.psv
p000508.psv
p000509.psv
p000510.psv
p000511.psv
p000512.psv
p000513.psv
p000514.psv
p000515.psv
p000516.psv
p000517.psv
p000518.psv
p000519.psv
p000520.psv
p000521.psv
p000522.psv
p000523.psv
p000524.psv
p000525.psv
p000526.psv
p000527.psv
p000528.psv
p000529.psv
p000530.psv
p000531.psv
p000532.psv
p000533.psv
p000534.psv
p000535.psv
p000536.psv
p000537.psv
p000538.psv
p000539.psv
p000540.psv
p000541.psv
p000542.psv
p000543.psv
p000544.psv
p000545.psv
p000546.psv
p000547.psv
p000548.psv
p000549.psv
p000550.psv
p000551.psv
p000552.psv
p000553.psv
p000554.psv
p000555.psv
p000556.psv
p000557.psv
p000558.psv
p000559.psv
p000560.psv
p000561.psv
p000562.psv
p000563.psv
p000564.psv
p000565.psv
p000566.psv
p000567.psv
p000568.psv
p000569.psv
p000570.psv
p000571.psv
p000572.psv
p000573.psv
p000574.psv
p000575.psv
p000576.psv
p000577.psv
p000578.psv
p000579.psv
p000580.psv
p000581.psv
p000582.psv
p000583.psv
p000584.psv
p000585.psv
p000586.psv
p000587.psv
p000588.psv
p000589.psv
p000590.psv
p000591.psv
p000592.psv
p000593.psv
p000594.psv
p000595.psv
p000596.psv
p000597.psv
p000598.psv
p000599.psv
p000600.psv
p000601.psv
p000602.psv
p000603.psv
p000604.psv
p000605.psv
p000606.psv
p000607.psv
p000608.psv
p000609.psv
p000610.psv
p000611.psv
p000612.psv
p000613.psv
p000614.psv
p000615.psv
p000616.psv
p000617.psv
p000618.psv
p000619.psv
p000620.psv
p000621.psv
p000622.psv
p000623.psv
p000624.psv
p000625.psv
p000626.psv
p000627.psv
p000628.psv
p000629.psv
p000630.psv
p000631.psv
p000632.psv
p000633.psv
p000634.psv
p000635.psv
p000636.psv
p000637.psv
p000638.psv
p000639.psv
p000640.psv
p000641.psv
p000642.psv
p000643.psv
p000644.psv
p000645.psv
p000646.psv
p000647.psv
p000648.psv
p000649.psv
p000650.psv
p000651.psv
p000652.psv
p000653.psv
p000654.psv
p000655.psv
p000656.psv
p000657.psv
p000658.psv
p000659.psv
p000660.psv
p000661.psv
p000662.psv
p000663.psv
p000664.psv
p000665.psv
p000666.psv
p000667.psv
p000668.psv
p000669.psv
p000670.psv
p000671.psv
p000672.psv
p000673.psv
p000674.psv
p000675.psv
p000676.psv
p000677.psv
p000678.psv
p000679.psv
p000680.psv
p000681.psv
p000682.psv
p000683.psv
p000684.psv
p000685.psv
p000686.psv
p000687.psv
p000688.psv
p000689.psv
p000690.psv
p000691.psv
p000692.psv
p000693.psv
p000694.psv
p000695.psv
p000696.psv
p000697.psv
p000698.psv
p000699.psv
p000700.psv
p000701.psv
p000702.psv
p000703.psv
p000704.psv
p000705.psv
p000706.psv
p000707.psv
p000708.psv
p000709.psv
p000710.psv
p000711.psv
p000712.psv
p000713.psv
p000714.psv
p000715.psv
p000716.psv
p000717.psv
p000718.psv
p000719.psv
p000720.psv
p000721.psv
p000722.psv
p000723.psv
p000724.psv
p000725.psv
p000726.psv
p000727.psv
p000728.psv
p000729.psv
p000730.psv
p000731.psv
p000732.psv
p000733.psv
p000734.psv
p000735.psv
p000736.psv
p000737.psv
p000738.psv
p000739.psv
p000740.psv
p000741.psv
p000742.psv
p000743.psv
p000744.psv
p000745.psv
p000746.psv
p000747.psv
p000748.psv
p000749.psv
p000750.psv
p000751.psv
p000752.psv
p000753.psv
p000754.psv
p000755.psv
p000756.psv
p000757.psv
p000758.psv
p000759.psv
p000760.psv
p000761.psv
p000762.psv
p000763.psv
p000764.psv
p000765.psv
p000766.psv
p000767.psv
p000768.psv
p000769.psv
p000770.psv
p000771.psv
p000772.psv
p000773.psv
p000774.psv
p000775.psv
p000776.psv
p000777.psv
p000778.psv
p000779.psv
p000780.psv
p000781.psv
p000782.psv
p000783.psv
p000784.psv
p000785.psv
p000786.psv
p000787.psv
p000788.psv
p000789.psv
p000790.psv
p000791.psv
p000792.psv
p000793.psv
p000794.psv
p000795.psv
p000796.psv
p000797.psv
p000798.psv
p000799.psv
p000800.psv
p000801.psv
p000802.psv
p000803.psv
p000804.psv
p000805.psv
p000806.psv
p000807.psv
p000808.psv
p000809.psv
p000810.psv
p000811.psv
p000812.psv
p000813.psv
p000814.psv
p000815.psv
p000816.psv
p000817.psv
p000818.psv
p000819.psv
p000820.psv
p000821.psv
p000822.psv
p000823.psv
p000824.psv
p000825.psv
p000826.psv
p000827.psv
p000828.psv
p000829.psv
p000830.psv
p000831.psv
p000832.psv
p000833.psv
p000834.psv
p000835.psv
p000836.psv
p000837.psv
p000838.psv
p000839.psv
p000840.psv
p000841.psv
p000842.psv
p000843.psv
p000844.psv
p000845.psv
p000846.psv
p000847.psv
p000848.psv
p000849.psv
p000850.psv
p000851.psv
p000852.psv
p000853.psv
p000854.psv
p000855.psv
p000856.psv
p000857.psv
p000858.psv
p000859.psv
p000860.psv
p000861.psv
p000862.psv
p000863.psv
p000864.psv
p000865.psv
p000866.psv
p000867.psv
p000868.psv
p000869.psv
p000870.psv
p000871.psv
p000872.psv
p000873.psv
p000874.psv
p000875.psv
p000876.psv
p000877.psv
p000878.psv
p000879.psv
p000880.psv
p000881.psv
p000882.psv
p000883.psv
p000884.psv
p000885.psv
p000886.psv
p000887.psv
p000888.psv
p000889.psv
p000890.psv
p000891.psv
p000892.psv
p000893.psv
p000894.psv
p000895.psv
p000896.psv
p000897.psv
p000898.psv
p000899.psv
p000900.psv
p000901.psv
p000902.psv
p000903.psv
p000904.psv
p000905.psv
p000906.psv
p000907.psv
p000908.psv
p000909.psv
p000910.psv
p000911.psv
p000912.psv
p000913.psv
p000914.psv
p000915.psv
p000916.psv
p000917.psv
p000918.psv
p000919.psv
p000920.psv
p000921.psv
p000922.psv
p000923.psv
p000924.psv
p000925.psv
p000926.psv
p000927.psv
p000928.psv
p000929.psv
p000930.psv
p000931.psv
p000932.psv
p000933.psv
p000934.psv
p000935.psv
p000936.psv
p000937.psv
p000938.psv
p000939.psv
p000940.psv
p000941.psv
p000942.psv
p000943.psv
p000944.psv
p000945.psv
p000946.psv
p000947.psv
p000948.psv
p000949.psv
p000950.psv
p000951.psv
p000952.psv
p000953.psv
p000954.psv
p000955.psv
p000956.psv
p000957.psv
p000958.psv
p000959.psv
p000960.psv
p000961.psv
p000962.psv
p000963.psv
p000964.psv
p000965.psv
p000966.psv
p000967.psv
p000968.psv
p000969.psv
p000970.psv
p000971.psv
p000972.psv
p000973.psv
p000974.psv
p000975.psv
p000976.psv
p000977.psv
p000978.psv
p000979.psv
p000980.psv
p000981.psv
p000982.psv
p000983.psv
p000984.psv
p000985.psv
p000986.psv
p000987.psv
p000988.psv
p000989.psv
p000990.psv
p000991.psv
p000992.psv
p000993.psv
p000994.psv
p000995.psv
p000996.psv
p000997.psv
p000998.psv
p000999.psv
p001000.psv
p001001.psv
p001002.psv
p001003.psv
p001004.psv
p001005.psv
p001006.psv
p001007.psv
p001008.psv
p001009.psv
p001010.psv
p001011.psv
p001012.psv
p001013.psv
p001014.psv
p001015.psv
p001016.psv
p001017.psv
p001018.psv
p001019.psv
p001020.psv
p001021.psv
p001022.psv
p001023.psv
p001024.psv
p001025.psv
p001026.psv
p001027.psv
p001028.psv
p001029.psv
p001030.psv
p001031.psv
p001032.psv
p001033.psv
p001034.psv
p001035.psv
p001036.psv
p001037.psv
p001038.psv
p001039.psv
p001040.psv
p001041.psv
p001042.psv
p001043.psv
p001044.psv
p001045.psv
p001046.psv
p001047.psv
p001048.psv
p001049.psv
p001050.psv
p001051.psv
p001052.psv
p001053.psv
p001054.psv
p001055.psv
p001056.psv
p001057.psv
p001058.psv
p001059.psv
p001060.psv
p001061.psv
p001062.psv
p001063.psv
p001064.psv
p001065.psv
p001066.psv
p001067.psv
p001068.psv
p001069.psv
p001070.psv
p001071.psv
p001072.psv
p001073.psv
p001074.psv
p001075.psv
p001076.psv
p001077.psv
p001078.psv
p001079.psv
p001080.psv
p001081.psv
p001082.psv
p001083.psv
p001084.psv
p001085.psv
p001086.psv
p001087.psv
p001088.psv
p001089.psv
p001090.psv
p001091.psv
p001092.psv
p001093.psv
p001094.psv
p001095.psv
p001096.psv
p001097.psv
p001098.psv
p001099.psv
p001100.psv
p001101.psv
p001102.psv
p001103.psv
p001104.psv
p001105.psv
p001106.psv
p001107.psv
p001108.psv
p001109.psv
p001110.psv
p001111.psv
p001112.psv
p001113.psv
p001114.psv
p001115.psv
p001116.psv
p001117.psv
p001118.psv
p001119.psv
p001120.psv
p001121.psv
p001122.psv
p001123.psv
p001124.psv
p001125.psv
p001126.psv
p001127.psv
p001128.psv
p001129.psv
p001130.psv
p001131.psv
p001132.psv
p001133.psv
p001134.psv
p001135.psv
p001136.psv
p001137.psv
p001138.psv
p001139.psv
p001140.psv
p001141.psv
p001142.psv
p001143.psv
p001144.psv
p001145.psv
p001146.psv
p001147.psv
p001148.psv
p001149.psv
p001150.psv
p001151.psv
p001152.psv
p001153.psv
p001154.psv
p001155.psv
p001156.psv
p001157.psv
p001158.psv
p001159.psv
p001160.psv
p001161.psv
p001162.psv
p001163.psv
p001164.psv
p001165.psv
p001166.psv
p001167.psv
p001168.psv
p001169.psv
p001170.psv
p001171.psv
p001172.psv
p001173.psv
p001174.psv
p001175.psv
p001176.psv
p001177.psv
p001178.psv
p001179.psv
p001180.psv
p001181.psv
p001182.psv
p001183.psv
p001184.psv
p001185.psv
p001186.psv
p001187.psv
p001188.psv
p001189.psv
p001190.psv
p001191.psv
p001192.psv
p001193.psv
p001194.psv
p001195.psv
p001196.psv
p001197.psv
p001198.psv
p001199.psv
p001200.psv
p001201.psv
p001202.psv
p001203.psv
p001204.psv
p001205.psv
p001206.psv
p001207.psv
p001208.psv
p001209.psv
p001210.psv
p001211.psv
p001212.psv
p001213.psv
p001214.psv
p001215.psv
p001216.psv
p001217.psv
p001218.psv
p001219.psv
p001220.psv
p001221.psv
p001222.psv
p001223.psv
p001224.psv
p001225.psv
p001226.psv
p001227.psv
p001228.psv
p001229.psv
p001230.psv
p001231.psv
p001232.psv
p001233.psv
p001234.psv
p001235.psv
p001236.psv
p001237.psv
p001238.psv
p001239.psv
p001240.psv
p001241.psv
p001242.psv
p001243.psv
p001244.psv
p001245.psv
p001246.psv
p001247.psv
p001248.psv
p001249.psv
p001250.psv
p001251.psv
p001252.psv
p001253.psv
p001254.psv
p001255.psv
p001256.psv
p001257.psv
p001258.psv
p001259.psv
p001260.psv
p001261.psv
p001262.psv
p001263.psv
p001264.psv
p001265.psv
p001266.psv
p001267.psv
p001268.psv
p001269.psv
p001270.psv
p001271.psv
p001272.psv
p001273.psv
p001274.psv
p001275.psv
p001276.psv
p001277.psv
p001278.psv
p001279.psv
p001280.psv
p001281.psv
p001282.psv
p001283.psv
p001284.psv
p001285.psv
p001286.psv
p001287.psv
p001288.psv
p001289.psv
p001290.psv
p001291.psv
p001292.psv
p001293.psv
p001294.psv
p001295.psv
p001296.psv
p001297.psv
p001298.psv
p001299.psv
p001300.psv
p001301.psv
p001302.psv
p001303.psv
p001304.psv
p001305.psv
p001306.psv
p001307.psv
p001308.psv
p001309.psv
p001310.psv
p001311.psv
p001312.psv
p001313.psv
p001314.psv
p001315.psv
p001316.psv
p001317.psv
p001318.psv
p001319.psv
p001320.psv
p001321.psv
p001322.psv
p001323.psv
p001324.psv
p001325.psv
p001326.psv
p001327.psv
p001328.psv
p001329.psv
p001330.psv
p001331.psv
p001332.psv
p001333.psv
p001334.psv
p001335.psv
p001336.psv
p001337.psv
p001338.psv
p001339.psv
p001340.psv
p001341.psv
p001342.psv
p001343.psv
p001344.psv
p001345.psv
p001346.psv
p001347.psv
p001348.psv
p001349.psv
p001350.psv
p001351.psv
p001352.psv
p001353.psv
p001354.psv
p001355.psv
p001356.psv
p001357.psv
p001358.psv
p001359.psv
p001360.psv
p001361.psv
p001362.psv
p001363.psv
p001364.psv
p001365.psv
p001366.psv
p001367.psv
p001368.psv
p001369.psv
p001370.psv
p001371.psv
p001372.psv
p001373.psv
p001374.psv
p001375.psv
p001376.psv
p001377.psv
p001378.psv
p001379.psv
p001380.psv
p001381.psv
p001382.psv
p001383.psv
p001384.psv
p001385.psv
p001386.psv
p001387.psv
p001388.psv
p001389.psv
p001390.psv
p001391.psv
p001392.psv
p001393.psv
p001394.psv
p001395.psv
p001396.psv
p001397.psv
p001398.psv
p001399.psv
p001400.psv
p001401.psv
p001402.psv
p001403.psv
p001404.psv
p001405.psv
p001406.psv
p001407.psv
p001408.psv
p001409.psv
p001410.psv
p001411.psv
p001412.psv
p001413.psv
p001414.psv
p001415.psv
p001416.psv
p001417.psv
p001418.psv
p001419.psv
p001420.psv
p001421.psv
p001422.psv
p001423.psv
p001424.psv
p001425.psv
p001426.psv
p001427.psv
p001428.psv
p001429.psv
p001430.psv
p001431.psv
p001432.psv
p001433.psv
p001434.psv
p001435.psv
p001436.psv
p001437.psv
p001438.psv
p001439.psv
p001440.psv
p001441.psv
p001442.psv
p001443.psv
p001444.psv
p001445.psv
p001446.psv
p001447.psv
p001448.psv
p001449.psv
p001450.psv
p001451.psv
p001452.psv
p001453.psv
p001454.psv
p001455.psv
p001456.psv
p001457.psv
p001458.psv
p001459.psv
p001460.psv
p001461.psv
p001462.psv
p001463.psv
p001464.psv
p001465.psv
p001466.psv
p001467.psv
p001468.psv
p001469.psv
p001470.psv
p001471.psv
p001472.psv
p001473.psv
p001474.psv
p001475.psv
p001476.psv
p001477.psv
p001478.psv
p001479.psv
p001480.psv
p001481.psv
p001482.psv
p001483.psv
p001484.psv
p001485.psv
p001486.psv
p001487.psv
p001488.psv
p001489.psv
p001490.psv
p001491.psv
p001492.psv
p001493.psv
p001494.psv
p001495.psv
p001496.psv
p001497.psv
p001498.psv
p001499.psv
p001500.psv
p001501.psv
p001502.psv
p001503.psv
p001504.psv
p001505.psv
p001506.psv
p001507.psv
p001508.psv
p001509.psv
p001510.psv
p001511.psv
p001512.psv
p001513.psv
p001514.psv
p001515.psv
p001516.psv
p001517.psv
p001518.psv
p001519.psv
p001520.psv
p001521.psv
p001522.psv
p001523.psv
p001524.psv
p001525.psv
p001526.psv
p001527.psv
p001528.psv
p001529.psv
p001530.psv
p001531.psv
p001532.psv
p001533.psv
p001534.psv
p001535.psv
p001536.psv
p001537.psv
p001538.psv
p001539.psv
p001540.psv
p001541.psv
p001542.psv
p001543.psv
p001544.psv
p001545.psv
p001546.psv
p001547.psv
p001548.psv
p001549.psv
p001550.psv
p001551.psv
p001552.psv
p001553.psv
p001554.psv
p001555.psv
p001556.psv
p001557.psv
p001558.psv
p001559.psv
p001560.psv
p001561.psv
p001562.psv
p001563.psv
p001564.psv
p001565.psv
p001566.psv
p001567.psv
p001568.psv
p001569.psv
p001570.psv
p001571.psv
p001572.psv
p001573.psv
p001574.psv
p001575.psv
p001576.psv
p001577.psv
p001578.psv
p001579.psv
p001580.psv
p001581.psv
p001582.psv
p001583.psv
p001584.psv
p001585.psv
p001586.psv
p001587.psv
p001588.psv
p001589.psv
p001590.psv
p001591.psv
p001592.psv
p001593.psv
p001594.psv
p001595.psv
p001596.psv
p001597.psv
p001598.psv
p001599.psv
p001600.psv
p001601.psv
p001602.psv
p001603.psv
p001604.psv
p001605.psv
p001606.psv
p001607.psv
p001608.psv
p001609.psv
p001610.psv
p001611.psv
p001612.psv
p001613.psv
p001614.psv
p001615.psv
p001616.psv
p001617.psv
p001618.psv
p001619.psv
p001620.psv
p001621.psv
p001622.psv
p001623.psv
p001624.psv
p001625.psv
p001626.psv
p001627.psv
p001628.psv
p001629.psv
p001630.psv
p001631.psv
p001632.psv
p001633.psv
p001634.psv
p001635.psv
p001636.psv
p001637.psv
p001638.psv
p001639.psv
p001640.psv
p001641.psv
p001642.psv
p001643.psv
p001644.psv
p001645.psv
p001646.psv
p001647.psv
p001648.psv
p001649.psv
p001650.psv
p001651.psv
p001652.psv
p001653.psv
p001654.psv
p001655.psv
p001656.psv
p001657.psv
p001658.psv
p001659.psv
p001660.psv
p001661.psv
p001662.psv
p001663.psv
p001664.psv
p001665.psv
p001666.psv

In [ ]:
import pickle
filename = data_path + '/raw_data.pickle'
with open(filename, 'rb') as f:
    train = pickle.load(f)

FileNotFoundError: [Errno 2] No such file or directory: '../Data/training_setA/raw_data.pickle'

In [ ]:
train = concat_from_manifest(MANIFEST)
#train = pd.read_csv("../Data/Dataset.csv")

NameError: name 'pd' is not defined

In [24]:
train.head()

,Unnamed: 0,Hour,HR,O2Sat,Temp,SBP,MAP,DBP,Resp,EtCO2,...,Fibrinogen,Platelets,Age,Gender,Unit1,Unit2,HospAdmTime,ICULOS,SepsisLabel,Patient_ID
0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,68.54,0,NaN,NaN,-0.02,1,0,17072
1,1,1,65.0,100.0,NaN,NaN,72.0,NaN,16.5,NaN,...,NaN,NaN,68.54,0,NaN,NaN,-0.02,2,0,17072
2,2,2,78.0,100.0,NaN,NaN,42.5,NaN,NaN,NaN,...,NaN,NaN,68.54,0,NaN,NaN,-0.02,3,0,17072
3,3,3,73.0,100.0,NaN,NaN,NaN,NaN,17.0,NaN,...,NaN,NaN,68.54,0,NaN,NaN,-0.02,4,0,17072
4,4,4,70.0,100.0,NaN,129.0,74.0,69.0,14.0,NaN,...,NaN,330.0,68.54,0,NaN,NaN,-0.02,5,0,17072

In [32]:
td_num = []
for i in range(len(train_id)):
    td_num.append(int(train_id[i][1:7]))

print(td_num)

[6337, 2882, 4243, 581, 15249, 8143, 14592, 3617, 6927, 8082, 12747, 17010, 130, 18440, 16408, 3293, 10364, 3014, 6889, 1942, 332, 761, 7413, 8485, 1733, 10982, 19821, 13397, 10419, 2041, 17041, 14365, 19301, 15019, 13727, 1574, 16646, 624, 14568, 14216, 2066, 12479, 15547, 17243, 17039, 16119, 16514, 19966, 3222, 15474, 10559, 18015, 17314, 10521, 6407, 16563, 365, 17487, 19118, 8087, 1783, 9103, 15348, 18864, 16211, 13927, 13639, 15868, 6988, 5009, 4705, 3409, 4641, 5769, 14945, 678, 173, 4268, 1549, 14605, 885, 3899, 11996, 15551, 7971, 11613, 14899, 9818, 6346, 11203, 5656, 9285, 16861, 11202, 7689, 4212, 19201, 15932, 9694, 15959, 12819, 11029, 8762, 10962, 17578, 4691, 12499, 7117, 10928, 5432, 6825, 17382, 16562, 19190, 19452, 3148, 18346, 11086, 10974, 13691, 18395, 17392, 18292, 17755, 19618, 3060, 10375, 16441, 7232, 17346, 7407, 17418, 14255, 16250, 19192, 19870, 4939, 3110, 11951, 20640, 7601, 12712, 11394, 5460, 860, 17665, 8492, 7592, 437, 4314, 3763, 10462, 11175, 16273, 4561, 20375, 3969, 18876, 5934, 14456, 11424, 7751, 19102, 17432, 7352, 7557, 616, 9626, 6846, 14860, 7777, 13944, 7227, 18853, 1612, 17023, 14137, 7300, 16242, 308, 10184, 2708, 13103, 7799, 1646, 18796, 9909, 18469, 9268, 15445, 2178, 15732, 8362, 3625, 16114, 15879, 1836, 18343, 17840, 19188, 1921, 5812, 12580, 13343, 5609, 4192, 8680, 8238, 13950, 20636, 2032, 19556, 18337, 2795, 13909, 15254, 3753, 2144, 7235, 14989, 3407, 19158, 17842, 13479, 8990, 4077, 15486, 7136, 12165, 10070, 14422, 14505, 14843, 13305, 5288, 17548, 253, 407, 20423, 2901, 13645, 2700, 8350, 3141, 3680, 19307, 20329, 3945, 15598, 16623, 18609, 18858, 5397, 10650, 6504, 1723, 11793, 4936, 9901, 11956, 2420, 12719, 569, 3298, 8223, 14303, 11873, 19636, 819, 12656, 12078, 3931, 7287, 17403, 6273, 7377, 8728, 103, 16595, 7082, 12362, 10238, 6316, 6854, 12233, 19575, 5526, 3702, 15087, 19035, 14238, 966, 14569, 9182, 11045, 15508, 9663, 20313, 19311, 15605, 9533, 13712, 12662, 8748, 5916, 5184, 11730, 1425, 18601, 11745, 6805, 5179, 9119, 14415, 11288, 13931, 18566, 8668, 11744, 5580, 17339, 17736, 114, 14574, 10052, 13913, 13518, 9043, 563, 2718, 1335, 11832, 6786, 1215, 12045, 18671, 15224, 18213, 15108, 11649, 12584, 6498, 14307, 7458, 9169, 14361, 16343, 20397, 11072, 1872, 593, 7467, 6972, 9232, 4965, 9655, 6178, 14850, 931, 6370, 17786, 838, 14837, 215, 13100, 10042, 12748, 2629, 3168, 14089, 1018, 11697, 4761, 8354, 3183, 19254, 5329, 3869, 14075, 14597, 10528, 13565, 18031, 12060, 8456, 15809, 16734, 18662, 16790, 18909, 8059, 14198, 14919, 18377, 10749, 13232, 4587, 13402, 82, 12476, 3461, 14633, 10523, 14798, 9871, 6748, 299, 6330, 16335, 3301, 429, 7454, 18654, 5747, 65, 11472, 2658, 11408, 14405, 14112, 9864, 3482, 5844, 19661, 137, 17838, 18097, 18843, 8246, 10759, 10055, 14284, 3114, 2578, 18988, 17927, 6699, 14826, 11911, 17213, 17007, 9031, 7441, 9357, 3131, 17397, 7646, 11155, 10682, 18009, 967, 2602, 14501, 368, 12696, 11567, 15225, 17974, 11413, 13658, 6450, 6616, 13805, 6948, 12630, 16111, 4108, 15563, 14700, 13535, 15327, 8317, 20631, 18851, 2220, 1523, 10486, 9617, 15176, 18570, 18225, 8695, 14612, 3493, 13624, 8204, 6693, 11315, 2701, 16836, 16327, 8486, 16838, 3002, 3502, 18466, 15667, 16590, 13981, 18464, 9052, 12923, 12281, 16953, 823, 16333, 19238, 10341, 2792, 10997, 10139, 16558, 8724, 17166, 385, 3314, 13404, 20552, 16814, 5271, 18822, 19199, 9660, 10636, 9431, 9537, 4059, 16174, 873, 14155, 13256, 2042, 16208, 6713, 1665, 15493, 7374, 9535, 4106, 20383, 20396, 10083, 12361, 507, 10012, 1195, 13233, 1962, 13330, 5276, 16424, 1017, 18080, 17100, 13088, 18892, 1323, 16813, 8948, 2570, 20341, 16256, 19187, 8153, 7615, 4832, 4096, 18022, 14065, 1075, 6319, 18402, 17951, 7049, 7337, 1431, 10258, 12831, 309, 7419, 14373, 12330, 14985, 6788, 6031, 10989, 12452, 2367, 2583, 16490, 10934, 3121, 19696, 5791, 19024, 11837, 20526, 7384, 13597, 900, 3460, 7230, 14623, 1613, 3221, 3247, 1162, 16104, 1554, 19165, 5396, 6821, 20338, 10823, 4017, 13912, 6795, 1506, 7842, 13674, 71, 17520, 2110, 1274, 10366, 4204, 6448, 4763, 10285, 14993, 1484, 289, 18836, 19916, 19500, 14251, 18920, 18856, 1856, 9966, 18211, 10035, 19147, 9515, 9049, 18501, 6383, 8951, 9955, 5232, 17765, 18117, 7220, 2062, 20340, 7295, 1748, 18906, 15234, 3571, 2076, 15458, 1206, 2642, 698, 2006, 15776, 3988, 14909, 207, 16143, 7357, 7929, 6366, 8984, 7649, 13072, 10149, 1002, 12827, 6905, 1131, 4149, 16824, 10446, 9908, 9892, 18470, 2897, 4206, 2203, 3843, 3195, 18847, 3588, 7245, 13503, 5724, 16279, 19434, 15032, 1263, 2429, 2635, 14495, 1960, 6115, 8021, 19272, 2861, 10228, 18703, 997, 3542, 16301, 8933, 11652, 8237, 19755, 4810, 13923, 16767, 20582, 2029, 12062, 15466, 2136, 2194, 7703, 9349, 18664, 10652, 9592, 2872, 8964, 8169, 12933, 883, 18716, 16280, 6059, 17332, 7143, 8453, 16360, 9373, 10182, 11277, 11527, 3372, 12600, 9949, 14275, 16586, 6252, 17161, 1059, 7952, 2331, 2880, 6736, 5685, 17933, 2925, 20326, 18181, 9787, 17581, 13989, 13707, 10991, 13918, 2449, 11725, 506, 4885, 10924, 3368, 17272, 17510, 15615, 13979, 11356, 3992, 736, 19296, 19886, 6560, 5514, 17776, 8275, 9359, 19482, 4813, 8876, 1967, 12970, 439, 3479, 2056, 3516, 6934, 4261, 12051, 8112, 20408, 14970, 19843, 4024, 6977, 1862, 20535, 3136, 8812, 17044, 7342, 7532, 16038, 11407, 5257, 9724, 6569, 9125, 12352, 12459, 4957, 11131, 2915, 6008, 4943, 16378, 13223, 1838, 12969, 16731, 1366, 2591, 16573, 15513, 1817, 19392, 5715, 14131, 3273, 14852, 4458, 7360, 2759, 1893, 9709, 7913, 4513, 15578, 20530, 16289, 19145, 14010, 17377, 2526, 3075, 3034, 19948, 10861, 11631, 2123, 20504, 9445, 18585, 14629, 18900, 13163, 2918, 17051, 11153, 10066, 17494, 20619, 15071, 17720, 2350, 16770, 12056, 9851, 15208, 17673, 8308, 17245, 1080, 14234, 13046, 11787, 574, 12830, 2944, 13340, 19512, 8147, 15926, 469, 6957, 7965, 17202, 19825, 15451, 11074, 15192, 1676, 15963, 5636, 18286, 5991, 12387, 18489, 14946, 5447, 9337, 19319, 11513, 5309, 18706, 12770, 292, 317, 18679, 2166, 13667, 15053, 10325, 19509, 6214, 17648, 3807, 4859, 2781, 7386, 13092, 16309, 16660, 11467, 17428, 18751, 9990, 4205, 13977, 14602, 3156, 342, 11457, 9271, 659, 11980, 20635, 10967, 13963, 14832, 10931, 11943, 16468, 5192, 15898, 14606, 10940, 5283, 8406, 4718, 15784, 3240, 9742, 15542, 2891, 11614, 12358, 4403, 13642, 3306, 13440, 193, 16791, 9040, 17617, 12400, 8885, 8423, 14729, 5870, 2364, 3434, 5196, 7770, 9919, 12424, 6876, 18499, 13794, 12395, 7214, 2950, 9833, 2453, 14731, 14253, 146, 10655, 14521, 11305, 7641, 15006, 14512, 136, 8000, 2608, 13838, 5332, 17071, 15656, 10280, 19797, 5816, 3524, 20000, 14966, 12322, 8307, 6250, 3481, 6060, 12162, 17320, 7948, 8195, 19939, 2530, 19580, 5804, 8003, 17781, 15158, 2210, 13067, 15011, 10465, 7863, 12088, 176, 16828, 9354, 12879, 10429, 9189, 18266, 15579, 11389, 4285, 17062, 15548, 18788, 18473, 15967, 10248, 2134, 14325, 9012, 2328, 4746, 3078, 7296, 15773, 8208, 15687, 14534, 10261, 19653, 18504, 7069, 8461, 5114, 12533, 9186, 10529, 8305, 14740, 7912, 14625, 1465, 10930, 3160, 274, 5706, 16454, 20549, 2690, 12050, 14038, 19529, 5442, 2902, 798, 9210, 18978, 13933, 8083, 19410, 10289, 9264, 10312, 14390, 19394, 17014, 7678, 17016, 8533, 14974, 108, 14782, 11798, 11842, 11429, 6612, 14376, 3742, 9814, 3005, 12914, 13126, 5720, 3613, 15539, 12006, 18615, 15441, 2522, 13017, 7631, 19438, 19369, 1610, 11701, 14938, 952, 10787, 16723, 10769, 17810, 19402, 6393, 1264, 16833, 9375, 19066, 2416, 15933, 11435, 5152, 5584, 2476, 16366, 7605, 12402, 17913, 16338, 14169, 10276, 8556, 10649, 10498, 870, 16522, 106, 7701, 1753, 12138, 266, 19746, 8850, 17058, 3547, 15166, 19918, 17507, 17271, 15789, 11217, 2500, 4717, 3642, 4772, 13019, 3507, 6314, 1914, 17746, 6553, 12960, 1006, 20516, 10509, 13622, 18529, 7728, 6142, 6520, 4820, 13692, 6297, 7060, 10209, 284, 9146, 6902, 646, 4293, 17274, 10295, 4783, 1848, 20538, 355, 7389, 3069, 4393, 13714, 19901, 8952, 19542, 8914, 1623, 4731, 11942, 2741, 1355, 3470, 18578, 7551, 19396, 6332, 12398, 10032, 16263, 20452, 16258, 6611, 7621, 7348, 3082, 9643, 15588, 1552, 13930, 13812, 3513, 2881, 7080, 13035, 14024, 11192, 14935, 2308, 3027, 16588, 6685, 11364, 7346, 13387, 20483, 19545, 14622, 15220, 11171, 2748, 17547, 12604, 18602, 3380, 8693, 2780, 18590, 8860, 19291, 5445, 8374, 13488, 15257, 3111, 2148, 1923, 17582, 16334, 15619, 8299, 6645, 17088, 3276, 14091, 1177, 1476, 11318, 4759, 3875, 3855, 15847, 9105, 14055, 1495, 10254, 15289, 12473, 2603, 15154, 14100, 2743, 7602, 15814, 685, 11928, 10355, 554, 8581, 19210, 7936, 4338, 7501, 19748, 8263, 5974, 17458, 16331, 8958, 15290, 19862, 5757, 6173, 9342, 2934, 3845, 12625, 3816, 4377, 4793, 10597, 5809, 13033, 7394, 15962, 10168, 12866, 4613, 2447, 12887, 7898, 10839, 18776, 8715, 2406, 10888, 1429, 1233, 6815, 1832, 4247, 6761, 16688, 4258, 8219, 20416, 13311, 13723, 16501, 4524, 16047, 6461, 151, 12451, 5068, 288, 10731, 16141, 16705, 9111, 5625, 5513, 9510, 15979, 1051, 3874, 18170, 4439, 1905, 1585, 11563, 17555, 9265, 6435, 8327, 7759, 4083, 138, 6820, 10162, 16076, 19933, 10702, 13023, 9305, 18819, 9854, 6935, 8587, 13542, 7806, 13050, 9165, 16502, 3848, 2394, 14681, 10206, 4754, 18722, 12985, 14447, 20495, 635, 18441, 16428, 15729, 3986, 20522, 9488, 3414, 17837, 1816, 15370, 8047, 14464, 3962, 10483, 144, 18913, 16293, 11903, 17414, 10457, 888, 14493, 6993, 9051, 1916, 6828, 12437, 6267, 13115, 3031, 7696, 18008, 2277, 19246, 18088, 5314, 7625, 14722, 12161, 13711, 17131, 442, 1796, 11624, 18861, 17542, 10076, 3297, 5205, 9868, 5977, 5107, 10943, 19212, 3737, 1130, 17429, 10450, 13169, 11609, 2090, 16495, 6089, 8455, 1297, 17573, 6953, 12833, 12875, 12751, 19525, 11230, 2075, 17133, 19826, 1551, 15380, 13400, 11219, 19156, 17263, 19359, 17539, 6613, 15174, 3583, 18810, 1409, 19910, 16598, 8233, 10069, 13326, 12441, 5762, 1329, 19986, 11310, 19465, 7715, 13997, 10091, 19075, 13973, 15535, 14736, 16048, 5774, 7124, 15005, 7244, 7708, 9149, 1656, 16398, 8025, 9775, 3739, 18344, 13248, 6581, 16737, 17888, 4081, 4809, 10789, 16284, 159, 10491, 6623, 11292, 17252, 16973, 14560, 11972, 8775, 12192, 11193, 12955, 2176, 16269, 9677, 13536, 6507, 15298, 17571, 3003, 6745, 15028, 5292, 17483, 4501, 4160, 12197, 7017, 10761, 4201, 10172, 45, 10760, 4424, 15413, 15004, 13000, 11939, 18728, 16155, 4735, 3764, 14969, 17002, 4050, 10436, 5133, 13513, 16907, 7925, 15328, 6829, 11855, 1214, 5576, 19810, 20627, 17948, 10197, 16985, 5223, 7706, 728, 6036, 2334, 1119, 6690, 691, 19037, 5994, 15030, 7541, 20537, 14462, 8478, 14122, 10099, 90, 12044, 10944, 18824, 2656, 12661, 19454, 17896, 19206, 13417, 19774, 2993, 14973, 7753, 19321, 13231, 19601, 12105, 1716, 15189, 15514, 19753, 5638, 1820, 13183, 6688, 9397, 11053, 1892, 10551, 1903, 13432, 1882, 9366, 7655, 1422, 12164, 16961, 9238, 12245, 16178, 9471, 12910, 15126, 10432, 3180, 13636, 18896, 2302, 2254, 4624, 1383, 14012, 2025, 1878, 10765, 4643, 13496, 3662, 10329, 19403, 12337, 9028, 18544, 19314, 4550, 19550, 14992, 10296, 1508, 7011, 18016, 4749, 10980, 14060, 2618, 6926, 2034, 18221, 10646, 15306, 11357, 15496, 19180, 15359, 8389, 16106, 14309, 11206, 2721, 7320, 16163, 2490, 9912, 10386, 8462, 15751, 20536, 7025, 9760, 18950, 8261, 9852, 16717, 17170, 4264, 15816, 12563, 8399, 9258, 9145, 18121, 12859, 19386, 1924, 13101, 16726, 6885, 182, 1303, 18868, 9673, 510, 18281, 16781, 16926, 7015, 7127, 9298, 7008, 14369, 15362, 18401, 18433, 3497, 18783, 5567, 92, 14168, 422, 12945, 19418, 9362, 1365, 9545, 17640, 19893, 2926, 12210, 7506, 6275, 8048, 13357, 19115, 5355, 1776, 2150, 6983, 11041, 15806, 18596, 16140, 19533, 17745, 8912, 3736, 9835, 12646, 16859, 4398, 11592, 3081, 8689, 4019, 4307, 7542, 1257, 19538, 17255, 684, 10596, 19404, 11270, 9307, 3892, 7312, 4600, 11431, 6942, 4122, 5466, 13786, 12962, 3987, 243, 259, 7986, 15263, 12963, 4968, 15388, 14387, 18986, 15286, 16098, 15813, 15095, 41, 15693, 11302, 14895, 19198, 11850, 16274, 2784, 339, 84, 3422, 789, 1744, 12994, 16240, 8790, 749, 14775, 12806, 19728, 19315, 17408, 4601, 14660, 15016, 15867, 10063, 15949, 3911, 14847, 13299, 19912, 8687, 14046, 880, 12422, 6880, 19365, 320, 11073, 13384, 7317, 8805, 15058, 19878, 5051, 10817, 14477, 16010, 8509, 8107, 5931, 16616, 4459, 11000, 1330, 2659, 19275, 12986, 3432, 17889, 2348, 10260, 19686, 4505, 2120, 10270, 8670, 10065, 4581, 17436, 17572, 1013, 16248, 16325, 6746, 6887, 12598, 5109, 18569, 18388, 17508, 11924, 19622, 10315, 4169, 6419, 12391, 15403, 19398, 15341, 12652, 19230, 5574, 1589, 8806, 19421, 10768, 2338, 13093, 17678, 1932, 9004, 7408, 18912, 10150, 10730, 4240, 12171, 1414, 16525, 17699, 15035, 19908, 13078, 17350, 13419, 4588, 9360, 16721, 13200, 3919, 14777, 4825, 16342, 7550, 17439, 5746, 4434, 6822, 15790, 20395, 17829, 5968, 13641, 7972, 1522, 7319, 17822, 12642, 8698, 13546, 1738, 19765, 12889, 17224, 3865, 15165, 3250, 16972, 15025, 15768, 14655, 19111, 14326, 16924, 1191, 16819, 3086, 6414, 17954, 16011, 6890, 13951, 18482, 3535, 840, 12082, 10663, 15301, 18965, 8935, 352, 13970, 15727, 14468, 120, 2403, 17077, 17238, 3707, 18918, 7554, 3933, 10475, 8483, 15039, 13455, 11717, 245, 2499, 16739, 17177, 12777, 18369, 18536, 1400, 15849, 7970, 2035, 15160, 13607, 18196, 4102, 6301, 15980, 5751, 9492, 9147, 13560, 13648, 10752, 16560, 4126, 5148, 9410, 15124, 2135, 6153, 17594, 5858, 3353, 17009, 1735, 2704, 5045, 8166, 19054, 5965, 12109, 16856, 14703, 13020, 11116, 886, 8985, 908, 5170, 5481, 434, 2940, 9055, 5479, 17114, 160, 5484, 6456, 18700, 1003, 16518, 7269, 17782, 1172, 18171, 15303, 15601, 5924, 14554, 1814, 12022, 16995, 17181, 1791, 343, 6552, 4216, 9611, 10829, 16099, 20451, 4364, 8211, 15952, 2557, 17127, 5980, 853, 15284, 1512, 17349, 19069, 8807, 17625, 8410, 9640, 6462, 2487, 7111, 5678, 5433, 4432, 1309, 7152, 16496, 12671, 5464, 11442, 1298, 12490, 20321, 8129, 15534, 17290, 15049, 4055, 12697, 9548, 4577, 10025, 9747, 15109, 13031, 14586, 17472, 14176, 1404, 9858, 12893, 13153, 5639, 1778, 13316, 294, 13601, 15562, 10857, 18732, 16806, 893, 12472, 13954, 5613, 2968, 9097, 9183, 5, 18123, 10921, 6340, 10481, 10322, 8536, 14972, 3245, 13014, 11783, 10557, 12300, 13141, 9168, 9967, 1773, 11948, 5499, 6717, 9385, 12936, 1981, 12293, 8495, 15067, 19558, 2296, 15540, 9887, 19108, 8534, 13380, 5382, 8465, 5981, 12899, 8699, 829, 5641, 11242, 7022, 6649, 19177, 16938, 15460, 15134, 19541, 14305, 10910, 7915, 13352, 19091, 3464, 5532, 6281, 1223, 19044, 16871, 13810, 10733, 13736, 20399, 6615, 8516, 4819, 3836, 15631, 1242, 6744, 5786, 14079, 415, 7028, 13934, 19000, 15862, 18502, 10064, 9378, 17421, 4442, 4959, 17577, 10212, 18750, 9581, 1852, 16172, 16581, 9214, 14475, 10953, 777, 16310, 8414, 1510, 5462, 538, 17094, 12286, 13839, 11604, 5630, 11122, 1772, 13851, 19171, 1287, 12944, 20310, 17256, 11890, 10485, 6293, 2845, 1381, 2180, 5703, 730, 19347, 16477, 83, 19292, 8866, 2189, 17936, 1669, 7793, 16300, 19059, 6584, 12820, 301, 10411, 10642, 1975, 5517, 14578, 7189, 16126, 10668, 4595, 18973, 10563, 5272, 12220, 6904, 5642, 16711, 16400, 9508, 502, 19530, 2769, 19894, 8663, 16217, 15961, 5975, 15125, 4542, 3880, 5089, 6058, 6986, 13888, 17908, 8348, 14400, 18523, 1079, 15394, 11546, 2991, 473, 7051, 17574, 6009, 12655, 6092, 4748, 2196, 8834, 257, 12058, 5570, 3058, 18966, 8343, 12785, 8117, 15024, 1056, 10216, 19448, 10828, 7908, 15241, 17157, 242, 4990, 8535, 5698, 12166, 20523, 10791, 10107, 20404, 5838, 18437, 18624, 9910, 16413, 19445, 3150, 13449, 11871, 6430, 4770, 6873, 10470, 2474, 12280, 18214, 10017, 759, 13178, 14610, 6097, 14299, 6843, 2425, 12907, 2464, 11477, 20369, 4025, 18174, 16577, 656, 14728, 3138, 11367, 9898, 10786, 323, 4580, 6793, 15557, 15825, 19008, 1444, 453, 8076, 2692, 19732, 16103, 2016, 16794, 12112, 9401, 12506, 17868, 8320, 1499, 15617, 15501, 6362, 12175, 9933, 19105, 14151, 714, 6874, 4511, 13566, 17603, 11240, 3426, 4886, 7992, 3045, 15955, 18725, 10701, 12838, 10342, 7616, 2012, 5412, 8902, 5745, 12702, 5696, 3748, 2995, 18520, 12121, 5384, 14663, 2823, 11091, 15512, 2475, 2063, 4701, 5979, 14171, 2883, 7183, 9776, 13448, 12926, 8607, 671, 14922, 19947, 17278, 493, 12728, 19760, 349, 18753, 1054, 4738, 2083, 7928, 20529, 5550, 13230, 16409, 1736, 14787, 1456, 7824, 7994, 16755, 10303, 9950, 11799, 11378, 12599, 17701, 4168, 857, 10229, 14942, 16504, 8510, 4181, 18805, 12093, 6465, 14329, 13699, 14397, 8073, 10004, 17445, 7347, 5280, 10019, 4712, 9252, 683, 8489, 16204, 19017, 10023, 2577, 2536, 8437, 9978, 9041, 12872, 1267, 2247, 7528, 19911, 12193, 1349, 5473, 6016, 10058, 10715, 3241, 956, 58, 9791, 8566, 12225, 15073, 4769, 852, 7849, 5970, 6802, 15183, 8038, 20377, 8801, 2105, 10621, 9870, 16363, 4515, 5159, 14768, 11544, 19216, 7525, 12862, 4737, 6228, 14015, 13612, 2469, 16568, 14078, 17618, 13297, 12141, 11888, 2010, 9836, 9089, 13043, 17522, 1044, 10546, 13310, 7787, 15437, 6776, 8827, 5474, 1636, 4537, 8740, 8780, 998, 4484, 15355, 17176, 19003, 18594, 975, 19675, 19095, 14392, 18208, 504, 9827, 549, 5689, 8194, 15232, 6356, 10427, 4232, 17191, 19151, 15320, 12726, 11862, 1136, 4482, 9254, 4752, 8755, 20478, 15271, 1166, 19907, 11414, 1794, 12984, 10567, 5415, 1953, 7570, 18227, 18972, 5027, 8505, 8672, 8098, 188, 10674, 15221, 20637, 15360, 4579, 14913, 15258, 16589, 369, 10896, 89, 7563, 19734, 19527, 7946, 19698, 1350, 15034, 6088, 14977, 14780, 2979, 19471, 17306, 11637, 8800, 12261, 8612, 6968, 3955, 16625, 11490, 19831, 5277, 16393, 2607, 3910, 16464, 16139, 4534, 1272, 11906, 19590, 12854, 9861, 4988, 18329, 1165, 16302, 2727, 5763, 12408, 19867, 11409, 16511, 6242, 14285, 15560, 10502, 5777, 12529, 19083, 9974, 17149, 11895, 2149, 13181, 7290, 2122, 5894, 17808, 17412, 16578, 8934, 4407, 14214, 11963, 18455, 15498, 15128, 14618, 7789, 18458, 5251, 5948, 15044, 11748, 9934, 19756, 707, 4551, 13205, 12606, 4750, 11015, 2051, 17843, 5247, 12183, 2782, 8451, 10626, 298, 2347, 9788, 1271, 12815, 16283, 14372, 10131, 17820, 18767, 17090, 19339, 18669, 16830, 18273, 3263, 14002, 9730, 12825, 13952, 1837, 7115, 2697, 12004, 2908, 49, 5922, 9578, 1599, 327, 11602, 17749, 11247, 2352, 18684, 15471, 99, 2008, 9129, 15992, 19818, 19466, 1958, 9810, 14451, 10520, 1156, 2825, 4980, 14053, 3462, 14144, 2592, 12124, 15799, 4948, 18064, 534, 1564, 20544, 4399, 18149, 13090, 738, 16433, 769, 6043, 8480, 16556, 11054, 18667, 16245, 12601, 13937, 17942, 4902, 6893, 18839, 9263, 916, 19182, 2716, 3200, 8236, 15029, 16100, 15351, 1190, 6908, 16391, 5182, 19781, 4744, 7796, 6048, 8005, 10072, 13274, 16457, 1799, 10370, 11280, 19026, 14667, 11207, 14341, 9159, 15272, 17653, 4057, 9439, 9907, 8972, 6571, 14726, 17115, 9383, 7366, 1991, 18407, 10003, 15666, 1380, 13899, 1706, 12137, 10008, 4955, 13443, 18895, 17696, 11588, 12693, 18936, 15008, 10006, 1200, 20430, 17534, 6774, 14249, 7604, 1388, 15700, 11020, 7950, 6268, 9447, 414, 2301, 16287, 11118, 8821, 12242, 11523, 5375, 11923, 3004, 11514, 15830, 12267, 6711, 15191, 19245, 4497, 1417, 2923, 2980, 6032, 1774, 19511, 18869, 20507, 5218, 2955, 9037, 4132, 5792, 7845, 6415, 1477, 1519, 10387, 9377, 18759, 14472, 16919, 7791, 16317, 11568, 5031, 17869, 119, 8569, 19710, 11950, 2807, 9066, 8841, 15238, 8515, 11265, 5632, 19414, 7577, 4805, 19136, 3717, 4841, 19899, 20622, 10278, 6422, 6570, 8893, 639, 3046, 4467, 887, 10335, 16003, 14596, 12775, 16942, 7866, 3560, 11777, 4327, 15571, 13562, 3485, 13895, 17654, 16792, 11579, 2146, 862, 16210, 821, 5300, 16271, 4574, 8252, 2617, 11104, 19280, 5839, 16743, 10164, 1397, 17626, 7185, 3767, 7064, 16153, 17416, 18713, 18880, 17877, 52, 3389, 10358, 6577, 14723, 7375, 9699, 11907, 2849, 5199, 20368, 2223, 19224, 18758, 13452, 3785, 3072, 6506, 7009, 8433, 3518, 8629, 6073, 16976, 13197, 3770, 1343, 5687, 7844, 16870, 4736, 8773, 4274, 18608, 12547, 4845, 17118, 19954, 2307, 19949, 9309, 15387, 9989, 6197, 10600, 15110, 15322, 565, 10770, 11493, 7208, 12592, 17242, 16524, 4283, 1786, 9464, 2843, 15509, 13504, 3917, 7381, 11770, 13189, 1530, 19559, 3703, 11107, 12042, 6171, 19085, 1928, 8635, 14607, 8395, 

In [33]:
train_concate = train[train.Patient_ID.isin(td_num)]

train_concate.to_csv("../Data/train_concate.csv",sep = '|')

In [ ]:
train_concate = pd.read_csv("../Data/train_concate.csv", sep = '|')

,Unnamed: 0.1,Unnamed: 0,Hour,HR,O2Sat,Temp,SBP,MAP,DBP,Resp,...,Fibrinogen,Platelets,Age,Gender,Unit1,Unit2,HospAdmTime,ICULOS,SepsisLabel,Patient_ID
0,43,0,0,75.5,95.0,37.44,135.0,88.33,NaN,24.5,...,NaN,NaN,46.32,1,NaN,NaN,-0.04,4,0,16153
1,44,1,1,84.0,95.0,37.22,124.0,81.33,NaN,22.0,...,NaN,NaN,46.32,1,NaN,NaN,-0.04,5,0,16153
2,45,2,2,89.0,96.0,NaN,132.0,84.00,NaN,24.0,...,NaN,NaN,46.32,1,NaN,NaN,-0.04,6,0,16153
3,46,3,3,85.0,95.0,NaN,140.0,87.33,NaN,22.0,...,NaN,NaN,46.32,1,NaN,NaN,-0.04,7,0,16153
4,47,4,4,83.0,94.0,NaN,108.0,76.67,NaN,21.0,...,NaN,260.0,46.32,1,NaN,NaN,-0.04,8,0,16153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
552834,790162,27,27,92.0,98.0,NaN,93.0,70.00,56.0,15.0,...,NaN,NaN,61.31,0,NaN,NaN,-8.17,33,0,11204
552835,790163,28,28,89.0,98.0,NaN,90.0,69.00,55.0,14.0,...,NaN,NaN,61.31,0,NaN,NaN,-8.17,34,0,11204
552836,790164,29,29,94.0,98.0,35.83,92.0,69.00,55.0,14.0,...,NaN,NaN,61.31,0,NaN,NaN,-8.17,35,0,11204
552837,790165,30,30,98.0,97.0,NaN,94.0,70.00,55.0,13.0,...,NaN,NaN,61.31,0,NaN,NaN,-8.17,36,0,11204
552838,790166,31,31,102.0,97.0,NaN,122.0,96.00,77.0,20.0,...,NaN,761.0,61.31,0,NaN,NaN,-8.17,37,0,11204

In [35]:
train_concate.shape

(552839, 44)

In [37]:
val_num = []
for i in range(len(val_id)):
    val_num.append(val_id[i][1:7])
    
val_concate = train[train.Patient_ID.isin(val_num)]

In [38]:
val_concate.to_csv('../Data/val_concate.csv', sep = '|')

In [99]:
pd.read_csv('/Users/Chili/Desktop/timeseries/new_project/val_concate.csv', sep = '|')

,HR,O2Sat,Temp,SBP,MAP,DBP,Resp,EtCO2,BaseExcess,HCO3,...,Fibrinogen,Platelets,Age,Gender,Unit1,Unit2,HospAdmTime,ICULOS,SepsisLabel,patient_id
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,75.91,0,0.0,1.0,-98.60,1,0,2
1,61.0,99.0,36.44,124.0,65.0,43.0,17.5,NaN,NaN,NaN,...,NaN,NaN,75.91,0,0.0,1.0,-98.60,2,0,2
2,64.0,98.0,NaN,125.0,64.0,41.0,27.0,NaN,NaN,NaN,...,NaN,NaN,75.91,0,0.0,1.0,-98.60,3,0,2
3,56.0,100.0,NaN,123.0,65.0,41.0,9.0,NaN,NaN,NaN,...,NaN,NaN,75.91,0,0.0,1.0,-98.60,4,0,2
4,66.0,99.0,NaN,120.0,67.0,43.0,23.0,NaN,NaN,NaN,...,NaN,NaN,75.91,0,0.0,1.0,-98.60,5,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118868,55.0,96.0,37.67,100.0,77.0,NaN,18.0,NaN,NaN,NaN,...,NaN,NaN,38.02,1,NaN,NaN,-0.03,11,0,20630
118869,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,38.02,1,NaN,NaN,-0.03,12,0,20630
118870,60.0,97.0,NaN,100.0,83.0,NaN,19.0,NaN,NaN,NaN,...,NaN,NaN,38.02,1,NaN,NaN,-0.03,13,0,20630
118871,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,38.02,1,NaN,NaN,-0.03,14,0,20630
118872,69.0,96.0,38.00,105.0,73.0,NaN,20.0,NaN,NaN,NaN,...,NaN,NaN,38.02,1,NaN,NaN,-0.03,15,0,20630

In [40]:
test_num = []
for i in range(len(test_id)):
    test_num.append(list(test_id)[i][1:7])
    
test_concate = train[train.Patient_ID.isin(test_num)]

In [41]:
test_concate.to_csv('../Data/test_concate.csv', sep = '|', index = False)

In [ ]:
pd.read_csv('../Data/test_concate.csv', sep = '|')

,HR,O2Sat,Temp,SBP,MAP,DBP,Resp,EtCO2,BaseExcess,HCO3,...,Fibrinogen,Platelets,Age,Gender,Unit1,Unit2,HospAdmTime,ICULOS,SepsisLabel,patient_id
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,45.76,0,1.0,0.0,-0.03,1,0,17
1,79.0,98.0,NaN,134.0,81.33,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,45.76,0,1.0,0.0,-0.03,2,0,17
2,81.0,98.0,NaN,121.0,80.33,NaN,16.0,NaN,NaN,NaN,...,NaN,NaN,45.76,0,1.0,0.0,-0.03,3,0,17
3,88.0,100.0,NaN,131.0,77.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,45.76,0,1.0,0.0,-0.03,4,0,17
4,86.0,100.0,NaN,143.0,89.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,45.76,0,1.0,0.0,-0.03,5,0,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118234,83.0,94.0,37.5,149.0,83.00,55.0,17.0,NaN,NaN,NaN,...,NaN,NaN,74.53,0,0.0,1.0,-59.09,23,0,20640
118235,74.0,93.0,37.5,147.0,77.00,50.0,15.0,NaN,NaN,NaN,...,NaN,NaN,74.53,0,0.0,1.0,-59.09,24,0,20640
118236,74.0,95.0,37.5,138.0,74.00,52.0,15.0,NaN,NaN,NaN,...,NaN,NaN,74.53,0,0.0,1.0,-59.09,25,0,20640
118237,71.0,97.0,37.4,135.0,73.33,59.0,14.0,NaN,NaN,NaN,...,NaN,NaN,74.53,0,0.0,1.0,-59.09,26,0,20640
118238,73.0,98.0,NaN,140.0,78.00,NaN,21.0,NaN,NaN,NaN,...,NaN,NaN,74.53,0,0.0,1.0,-59.09,27,0,20640