In [ ]:
import numpy as np
import pandas as pd
import os
from random import seed
from data_splitter import split_dataframe, concat_from_manifest
  
seed(1121)

In [ ]:
CHUNKS_DIR = "../Data"
MANIFEST   = f"{CHUNKS_DIR}/Dataset_manifest.txt"

In [11]:
data_path = '../Data/training_setA'
patient_path = os.path.join(data_path,"training")

In [3]:
patient_id = sorted(os.listdir(os.path.join(data_path,"training")))

In [ ]:
len_train = round(0.7*len(patient_id))+1
len_val = round(0.15*len(patient_id))
len_test = round(0.15*len(patient_id))
len_train + len_val + len_test == len(patient_id)

AA
AA
AA
AA
AA

In [5]:
len_train

14236

In [7]:
import random
train_id = random.sample(patient_id, len_train)
val_id = random.sample(sorted(set(patient_id) - set(train_id)), len_val)
test_id = set(patient_id) - set(train_id) - set(val_id)

## raw split

In [8]:
data_train = data_path + '/raw/training/'
data_val = data_path + '/raw/validation/'
data_test = data_path + '/raw/test/'

In [9]:
os.makedirs(data_train,exist_ok=True)
os.makedirs(data_val,exist_ok=True)
os.makedirs(data_test,exist_ok=True)

In [12]:
for p in train_id:
    df = pd.read_csv(patient_path + '/' + p, sep = "|")
    df.to_csv(data_train  + p, sep='|', index = False)

In [13]:
for p in val_id:
    df = pd.read_csv(patient_path + '/' + p, sep = "|")
    df.to_csv(data_val + p, sep='|', index = False)

In [14]:
for p in test_id:
    df = pd.read_csv(patient_path + '/' + p, sep = "|")
    df.to_csv(data_test + p, sep='|', index = False)

## Baseline

In [15]:
# function to fill missing values
def impute_missing_vals(df, attributes):

    """
    function that imputes missing values.
    
    @param df: dataframe that has missing values to be
               imputed
           attributes: list of String, attributes of dataframe
    @return df_clean: dataframe without missing values

    """
    
    """
    fill missing values by the closest values first
    ffill to fill missing values in the tail
    bfill to fill missing values in the head
    """
    # copy df
    df_clean = df.copy()
    for att in attributes:
        if df_clean[att].isnull().sum() == len(df_clean):
            df_clean[att] = df_clean[att].fillna(0)
        elif df_clean[att].isnull().sum() == len(df_clean) - 1:
            df_clean[att] = df_clean[att].ffill().bfill()
        else:
            df_clean[att] = df_clean[att].interpolate(method='nearest', limit_direction='both')
            df_clean[att] = df_clean[att].ffill().bfill()
    
    return df_clean

In [ ]:
# impute missing values and create clean dfs for all patients
for p in patient_id:
    
    # read in patient data
    df = pd.read_csv(patient_path + '/' + p, sep = "|")
    attributes = df.columns[:-1]
    
    # impute missing values
    df_clean = impute_missing_vals(df, attributes)
    
    # drop unit1 and unit2 with half missing values
    # because these two features have few information
    # drop EtCO2 with all missing values
    df_clean = df_clean.drop(['Unit1', 'Unit2', 'EtCO2'], axis=1)
    
    # save new patient data
    if p in train_id:
        save_path = data_path + '/baseline/train_baseline/'
        os.makedirs(save_path,exist_ok=True)
        df_clean.to_csv(save_path + p, sep='|', index = False)        
    
    elif p in val_id:
        save_path = data_path + '/baseline/val_baseline/'
        os.makedirs(save_path,exist_ok=True)
        df_clean.to_csv(save_path + p, sep='|', index = False)        
    
    else:
        
        save_path = data_path + '/baseline/test_baseline/'
        os.makedirs(save_path,exist_ok=True)
        df_clean.to_csv(save_path + p, sep='|', index = False)

In [ ]:
train = concat_from_manifest(MANIFEST)
#train = pd.read_csv("../Data/Dataset.csv")

In [24]:
train.head()

,Unnamed: 0,Hour,HR,O2Sat,Temp,SBP,MAP,DBP,Resp,EtCO2,...,Fibrinogen,Platelets,Age,Gender,Unit1,Unit2,HospAdmTime,ICULOS,SepsisLabel,Patient_ID
0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,68.54,0,NaN,NaN,-0.02,1,0,17072
1,1,1,65.0,100.0,NaN,NaN,72.0,NaN,16.5,NaN,...,NaN,NaN,68.54,0,NaN,NaN,-0.02,2,0,17072
2,2,2,78.0,100.0,NaN,NaN,42.5,NaN,NaN,NaN,...,NaN,NaN,68.54,0,NaN,NaN,-0.02,3,0,17072
3,3,3,73.0,100.0,NaN,NaN,NaN,NaN,17.0,NaN,...,NaN,NaN,68.54,0,NaN,NaN,-0.02,4,0,17072
4,4,4,70.0,100.0,NaN,129.0,74.0,69.0,14.0,NaN,...,NaN,330.0,68.54,0,NaN,NaN,-0.02,5,0,17072

In [32]:
td_num = []
for i in range(len(train_id)):
    td_num.append(int(train_id[i][1:7]))

print(td_num)

[6337, 2882, 4243, 581, 15249, 8143, 14592, 3617, 6927, 8082, 12747, 17010, 130, 18440, 16408, 3293, 10364, 3014, 6889, 1942, 332, 761, 7413, 8485, 1733, 10982, 19821, 13397, 10419, 2041, 17041, 14365, 19301, 15019, 13727, 1574, 16646, 624, 14568, 14216, 2066, 12479, 15547, 17243, 17039, 16119, 16514, 19966, 3222, 15474, 10559, 18015, 17314, 10521, 6407, 16563, 365, 17487, 19118, 8087, 1783, 9103, 15348, 18864, 16211, 13927, 13639, 15868, 6988, 5009, 4705, 3409, 4641, 5769, 14945, 678, 173, 4268, 1549, 14605, 885, 3899, 11996, 15551, 7971, 11613, 14899, 9818, 6346, 11203, 5656, 9285, 16861, 11202, 7689, 4212, 19201, 15932, 9694, 15959, 12819, 11029, 8762, 10962, 17578, 4691, 12499, 7117, 10928, 5432, 6825, 17382, 16562, 19190, 19452, 3148, 18346, 11086, 10974, 13691, 18395, 17392, 18292, 17755, 19618, 3060, 10375, 16441, 7232, 17346, 7407, 17418, 14255, 16250, 19192, 19870, 4939, 3110, 11951, 20640, 7601, 12712, 11394, 5460, 860, 17665, 8492, 7592, 437, 4314, 3763, 10462, 11175, 16273, 4561, 20375, 3969, 18876, 5934, 14456, 11424, 7751, 19102, 17432, 7352, 7557, 616, 9626, 6846, 14860, 7777, 13944, 7227, 18853, 1612, 17023, 14137, 7300, 16242, 308, 10184, 2708, 13103, 7799, 1646, 18796, 9909, 18469, 9268, 15445, 2178, 15732, 8362, 3625, 16114, 15879, 1836, 18343, 17840, 19188, 1921, 5812, 12580, 13343, 5609, 4192, 8680, 8238, 13950, 20636, 2032, 19556, 18337, 2795, 13909, 15254, 3753, 2144, 7235, 14989, 3407, 19158, 17842, 13479, 8990, 4077, 15486, 7136, 12165, 10070, 14422, 14505, 14843, 13305, 5288, 17548, 253, 407, 20423, 2901, 13645, 2700, 8350, 3141, 3680, 19307, 20329, 3945, 15598, 16623, 18609, 18858, 5397, 10650, 6504, 1723, 11793, 4936, 9901, 11956, 2420, 12719, 569, 3298, 8223, 14303, 11873, 19636, 819, 12656, 12078, 3931, 7287, 17403, 6273, 7377, 8728, 103, 16595, 7082, 12362, 10238, 6316, 6854, 12233, 19575, 5526, 3702, 15087, 19035, 14238, 966, 14569, 9182, 11045, 15508, 9663, 20313, 19311, 15605, 9533, 13712, 12662, 8748, 5916, 5184, 11730, 1425, 18601, 11745, 6805, 5179, 9119, 14415, 11288, 13931, 18566, 8668, 11744, 5580, 17339, 17736, 114, 14574, 10052, 13913, 13518, 9043, 563, 2718, 1335, 11832, 6786, 1215, 12045, 18671, 15224, 18213, 15108, 11649, 12584, 6498, 14307, 7458, 9169, 14361, 16343, 20397, 11072, 1872, 593, 7467, 6972, 9232, 4965, 9655, 6178, 14850, 931, 6370, 17786, 838, 14837, 215, 13100, 10042, 12748, 2629, 3168, 14089, 1018, 11697, 4761, 8354, 3183, 19254, 5329, 3869, 14075, 14597, 10528, 13565, 18031, 12060, 8456, 15809, 16734, 18662, 16790, 18909, 8059, 14198, 14919, 18377, 10749, 13232, 4587, 13402, 82, 12476, 3461, 14633, 10523, 14798, 9871, 6748, 299, 6330, 16335, 3301, 429, 7454, 18654, 5747, 65, 11472, 2658, 11408, 14405, 14112, 9864, 3482, 5844, 19661, 137, 17838, 18097, 18843, 8246, 10759, 10055, 14284, 3114, 2578, 18988, 17927, 6699, 14826, 11911, 17213, 17007, 9031, 7441, 9357, 3131, 17397, 7646, 11155, 10682, 18009, 967, 2602, 14501, 368, 12696, 11567, 15225, 17974, 11413, 13658, 6450, 6616, 13805, 6948, 12630, 16111, 4108, 15563, 14700, 13535, 15327, 8317, 20631, 18851, 2220, 1523, 10486, 9617, 15176, 18570, 18225, 8695, 14612, 3493, 13624, 8204, 6693, 11315, 2701, 16836, 16327, 8486, 16838, 3002, 3502, 18466, 15667, 16590, 13981, 18464, 9052, 12923, 12281, 16953, 823, 16333, 19238, 10341, 2792, 10997, 10139, 16558, 8724, 17166, 385, 3314, 13404, 20552, 16814, 5271, 18822, 19199, 9660, 10636, 9431, 9537, 4059, 16174, 873, 14155, 13256, 2042, 16208, 6713, 1665, 15493, 7374, 9535, 4106, 20383, 20396, 10083, 12361, 507, 10012, 1195, 13233, 1962, 13330, 5276, 16424, 1017, 18080, 17100, 13088, 18892, 1323, 16813, 8948, 2570, 20341, 16256, 19187, 8153, 7615, 4832, 4096, 18022, 14065, 1075, 6319, 18402, 17951, 7049, 7337, 1431, 10258, 12831, 309, 7419, 14373, 12330, 14985, 6788, 6031, 10989, 12452, 2367, 2583, 16490, 10934, 3121, 19696, 5791, 19024, 11837, 20526, 7384, 13597, 900, 3460, 7230, 14623, 1613, 3221, 3247, 1162, 16104, 1554, 19165, 5396, 6821, 20338, 10823, 4017, 13912, 6795, 1506, 7842, 13674, 71, 17520, 2110, 1274, 10366, 4204, 6448, 4763, 10285, 14993, 1484, 289, 18836, 19916, 19500, 14251, 18920, 18856, 1856, 9966, 18211, 10035, 19147, 9515, 9049, 18501, 6383, 8951, 9955, 5232, 17765, 18117, 7220, 2062, 20340, 7295, 1748, 18906, 15234, 3571, 2076, 15458, 1206, 2642, 698, 2006, 15776, 3988, 14909, 207, 16143, 7357, 7929, 6366, 8984, 7649, 13072, 10149, 1002, 12827, 6905, 1131, 4149, 16824, 10446, 9908, 9892, 18470, 2897, 4206, 2203, 3843, 3195, 18847, 3588, 7245, 13503, 5724, 16279, 19434, 15032, 1263, 2429, 2635, 14495, 1960, 6115, 8021, 19272, 2861, 10228, 18703, 997, 3542, 16301, 8933, 11652, 8237, 19755, 4810, 13923, 16767, 20582, 2029, 12062, 15466, 2136, 2194, 7703, 9349, 18664, 10652, 9592, 2872, 8964, 8169, 12933, 883, 18716, 16280, 6059, 17332, 7143, 8453, 16360, 9373, 10182, 11277, 11527, 3372, 12600, 9949, 14275, 16586, 6252, 17161, 1059, 7952, 2331, 2880, 6736, 5685, 17933, 2925, 20326, 18181, 9787, 17581, 13989, 13707, 10991, 13918, 2449, 11725, 506, 4885, 10924, 3368, 17272, 17510, 15615, 13979, 11356, 3992, 736, 19296, 19886, 6560, 5514, 17776, 8275, 9359, 19482, 4813, 8876, 1967, 12970, 439, 3479, 2056, 3516, 6934, 4261, 12051, 8112, 20408, 14970, 19843, 4024, 6977, 1862, 20535, 3136, 8812, 17044, 7342, 7532, 16038, 11407, 5257, 9724, 6569, 9125, 12352, 12459, 4957, 11131, 2915, 6008, 4943, 16378, 13223, 1838, 12969, 16731, 1366, 2591, 16573, 15513, 1817, 19392, 5715, 14131, 3273, 14852, 4458, 7360, 2759, 1893, 9709, 7913, 4513, 15578, 20530, 16289, 19145, 14010, 17377, 2526, 3075, 3034, 19948, 10861, 11631, 2123, 20504, 9445, 18585, 14629, 18900, 13163, 2918, 17051, 11153, 10066, 17494, 20619, 15071, 17720, 2350, 16770, 12056, 9851, 15208, 17673, 8308, 17245, 1080, 14234, 13046, 11787, 574, 12830, 2944, 13340, 19512, 8147, 15926, 469, 6957, 7965, 17202, 19825, 15451, 11074, 15192, 1676, 15963, 5636, 18286, 5991, 12387, 18489, 14946, 5447, 9337, 19319, 11513, 5309, 18706, 12770, 292, 317, 18679, 2166, 13667, 15053, 10325, 19509, 6214, 17648, 3807, 4859, 2781, 7386, 13092, 16309, 16660, 11467, 17428, 18751, 9990, 4205, 13977, 14602, 3156, 342, 11457, 9271, 659, 11980, 20635, 10967, 13963, 14832, 10931, 11943, 16468, 5192, 15898, 14606, 10940, 5283, 8406, 4718, 15784, 3240, 9742, 15542, 2891, 11614, 12358, 4403, 13642, 3306, 13440, 193, 16791, 9040, 17617, 12400, 8885, 8423, 14729, 5870, 2364, 3434, 5196, 7770, 9919, 12424, 6876, 18499, 13794, 12395, 7214, 2950, 9833, 2453, 14731, 14253, 146, 10655, 14521, 11305, 7641, 15006, 14512, 136, 8000, 2608, 13838, 5332, 17071, 15656, 10280, 19797, 5816, 3524, 20000, 14966, 12322, 8307, 6250, 3481, 6060, 12162, 17320, 7948, 8195, 19939, 2530, 19580, 5804, 8003, 17781, 15158, 2210, 13067, 15011, 10465, 7863, 12088, 176, 16828, 9354, 12879, 10429, 9189, 18266, 15579, 11389, 4285, 17062, 15548, 18788, 18473, 15967, 10248, 2134, 14325, 9012, 2328, 4746, 3078, 7296, 15773, 8208, 15687, 14534, 10261, 19653, 18504, 7069, 8461, 5114, 12533, 9186, 10529, 8305, 14740, 7912, 14625, 1465, 10930, 3160, 274, 5706, 16454, 20549, 2690, 12050, 14038, 19529, 5442, 2902, 798, 9210, 18978, 13933, 8083, 19410, 10289, 9264, 10312, 14390, 19394, 17014, 7678, 17016, 8533, 14974, 108, 14782, 11798, 11842, 11429, 6612, 14376, 3742, 9814, 3005, 12914, 13126, 5720, 3613, 15539, 12006, 18615, 15441, 2522, 13017, 7631, 19438, 19369, 1610, 11701, 14938, 952, 10787, 16723, 10769, 17810, 19402, 6393, 1264, 16833, 9375, 19066, 2416, 15933, 11435, 5152, 5584, 2476, 16366, 7605, 12402, 17913, 16338, 14169, 10276, 8556, 10649, 10498, 870, 16522, 106, 7701, 1753, 12138, 266, 19746, 8850, 17058, 3547, 15166, 19918, 17507, 17271, 15789, 11217, 2500, 4717, 3642, 4772, 13019, 3507, 6314, 1914, 17746, 6553, 12960, 1006, 20516, 10509, 13622, 18529, 7728, 6142, 6520, 4820, 13692, 6297, 7060, 10209, 284, 9146, 6902, 646, 4293, 17274, 10295, 4783, 1848, 20538, 355, 7389, 3069, 4393, 13714, 19901, 8952, 19542, 8914, 1623, 4731, 11942, 2741, 1355, 3470, 18578, 7551, 19396, 6332, 12398, 10032, 16263, 20452, 16258, 6611, 7621, 7348, 3082, 9643, 15588, 1552, 13930, 13812, 3513, 2881, 7080, 13035, 14024, 11192, 14935, 2308, 3027, 16588, 6685, 11364, 7346, 13387, 20483, 19545, 14622, 15220, 11171, 2748, 17547, 12604, 18602, 3380, 8693, 2780, 18590, 8860, 19291, 5445, 8374, 13488, 15257, 3111, 2148, 1923, 17582, 16334, 15619, 8299, 6645, 17088, 3276, 14091, 1177, 1476, 11318, 4759, 3875, 3855, 15847, 9105, 14055, 1495, 10254, 15289, 12473, 2603, 15154, 14100, 2743, 7602, 15814, 685, 11928, 10355, 554, 8581, 19210, 7936, 4338, 7501, 19748, 8263, 5974, 17458, 16331, 8958, 15290, 19862, 5757, 6173, 9342, 2934, 3845, 12625, 3816, 4377, 4793, 10597, 5809, 13033, 7394, 15962, 10168, 12866, 4613, 2447, 12887, 7898, 10839, 18776, 8715, 2406, 10888, 1429, 1233, 6815, 1832, 4247, 6761, 16688, 4258, 8219, 20416, 13311, 13723, 16501, 4524, 16047, 6461, 151, 12451, 5068, 288, 10731, 16141, 16705, 9111, 5625, 5513, 9510, 15979, 1051, 3874, 18170, 4439, 1905, 1585, 11563, 17555, 9265, 6435, 8327, 7759, 4083, 138, 6820, 10162, 16076, 19933, 10702, 13023, 9305, 18819, 9854, 6935, 8587, 13542, 7806, 13050, 9165, 16502, 3848, 2394, 14681, 10206, 4754, 18722, 12985, 14447, 20495, 635, 18441, 16428, 15729, 3986, 20522, 9488, 3414, 17837, 1816, 15370, 8047, 14464, 3962, 10483, 144, 18913, 16293, 11903, 17414, 10457, 888, 14493, 6993, 9051, 1916, 6828, 12437, 6267, 13115, 3031, 7696, 18008, 2277, 19246, 18088, 5314, 7625, 14722, 12161, 13711, 17131, 442, 1796, 11624, 18861, 17542, 10076, 3297, 5205, 9868, 5977, 5107, 10943, 19212, 3737, 1130, 17429, 10450, 13169, 11609, 2090, 16495, 6089, 8455, 1297, 17573, 6953, 12833, 12875, 12751, 19525, 11230, 2075, 17133, 19826, 1551, 15380, 13400, 11219, 19156, 17263, 19359, 17539, 6613, 15174, 3583, 18810, 1409, 19910, 16598, 8233, 10069, 13326, 12441, 5762, 1329, 19986, 11310, 19465, 7715, 13997, 10091, 19075, 13973, 15535, 14736, 16048, 5774, 7124, 15005, 7244, 7708, 9149, 1656, 16398, 8025, 9775, 3739, 18344, 13248, 6581, 16737, 17888, 4081, 4809, 10789, 16284, 159, 10491, 6623, 11292, 17252, 16973, 14560, 11972, 8775, 12192, 11193, 12955, 2176, 16269, 9677, 13536, 6507, 15298, 17571, 3003, 6745, 15028, 5292, 17483, 4501, 4160, 12197, 7017, 10761, 4201, 10172, 45, 10760, 4424, 15413, 15004, 13000, 11939, 18728, 16155, 4735, 3764, 14969, 17002, 4050, 10436, 5133, 13513, 16907, 7925, 15328, 6829, 11855, 1214, 5576, 19810, 20627, 17948, 10197, 16985, 5223, 7706, 728, 6036, 2334, 1119, 6690, 691, 19037, 5994, 15030, 7541, 20537, 14462, 8478, 14122, 10099, 90, 12044, 10944, 18824, 2656, 12661, 19454, 17896, 19206, 13417, 19774, 2993, 14973, 7753, 19321, 13231, 19601, 12105, 1716, 15189, 15514, 19753, 5638, 1820, 13183, 6688, 9397, 11053, 1892, 10551, 1903, 13432, 1882, 9366, 7655, 1422, 12164, 16961, 9238, 12245, 16178, 9471, 12910, 15126, 10432, 3180, 13636, 18896, 2302, 2254, 4624, 1383, 14012, 2025, 1878, 10765, 4643, 13496, 3662, 10329, 19403, 12337, 9028, 18544, 19314, 4550, 19550, 14992, 10296, 1508, 7011, 18016, 4749, 10980, 14060, 2618, 6926, 2034, 18221, 10646, 15306, 11357, 15496, 19180, 15359, 8389, 16106, 14309, 11206, 2721, 7320, 16163, 2490, 9912, 10386, 8462, 15751, 20536, 7025, 9760, 18950, 8261, 9852, 16717, 17170, 4264, 15816, 12563, 8399, 9258, 9145, 18121, 12859, 19386, 1924, 13101, 16726, 6885, 182, 1303, 18868, 9673, 510, 18281, 16781, 16926, 7015, 7127, 9298, 7008, 14369, 15362, 18401, 18433, 3497, 18783, 5567, 92, 14168, 422, 12945, 19418, 9362, 1365, 9545, 17640, 19893, 2926, 12210, 7506, 6275, 8048, 13357, 19115, 5355, 1776, 2150, 6983, 11041, 15806, 18596, 16140, 19533, 17745, 8912, 3736, 9835, 12646, 16859, 4398, 11592, 3081, 8689, 4019, 4307, 7542, 1257, 19538, 17255, 684, 10596, 19404, 11270, 9307, 3892, 7312, 4600, 11431, 6942, 4122, 5466, 13786, 12962, 3987, 243, 259, 7986, 15263, 12963, 4968, 15388, 14387, 18986, 15286, 16098, 15813, 15095, 41, 15693, 11302, 14895, 19198, 11850, 16274, 2784, 339, 84, 3422, 789, 1744, 12994, 16240, 8790, 749, 14775, 12806, 19728, 19315, 17408, 4601, 14660, 15016, 15867, 10063, 15949, 3911, 14847, 13299, 19912, 8687, 14046, 880, 12422, 6880, 19365, 320, 11073, 13384, 7317, 8805, 15058, 19878, 5051, 10817, 14477, 16010, 8509, 8107, 5931, 16616, 4459, 11000, 1330, 2659, 19275, 12986, 3432, 17889, 2348, 10260, 19686, 4505, 2120, 10270, 8670, 10065, 4581, 17436, 17572, 1013, 16248, 16325, 6746, 6887, 12598, 5109, 18569, 18388, 17508, 11924, 19622, 10315, 4169, 6419, 12391, 15403, 19398, 15341, 12652, 19230, 5574, 1589, 8806, 19421, 10768, 2338, 13093, 17678, 1932, 9004, 7408, 18912, 10150, 10730, 4240, 12171, 1414, 16525, 17699, 15035, 19908, 13078, 17350, 13419, 4588, 9360, 16721, 13200, 3919, 14777, 4825, 16342, 7550, 17439, 5746, 4434, 6822, 15790, 20395, 17829, 5968, 13641, 7972, 1522, 7319, 17822, 12642, 8698, 13546, 1738, 19765, 12889, 17224, 3865, 15165, 3250, 16972, 15025, 15768, 14655, 19111, 14326, 16924, 1191, 16819, 3086, 6414, 17954, 16011, 6890, 13951, 18482, 3535, 840, 12082, 10663, 15301, 18965, 8935, 352, 13970, 15727, 14468, 120, 2403, 17077, 17238, 3707, 18918, 7554, 3933, 10475, 8483, 15039, 13455, 11717, 245, 2499, 16739, 17177, 12777, 18369, 18536, 1400, 15849, 7970, 2035, 15160, 13607, 18196, 4102, 6301, 15980, 5751, 9492, 9147, 13560, 13648, 10752, 16560, 4126, 5148, 9410, 15124, 2135, 6153, 17594, 5858, 3353, 17009, 1735, 2704, 5045, 8166, 19054, 5965, 12109, 16856, 14703, 13020, 11116, 886, 8985, 908, 5170, 5481, 434, 2940, 9055, 5479, 17114, 160, 5484, 6456, 18700, 1003, 16518, 7269, 17782, 1172, 18171, 15303, 15601, 5924, 14554, 1814, 12022, 16995, 17181, 1791, 343, 6552, 4216, 9611, 10829, 16099, 20451, 4364, 8211, 15952, 2557, 17127, 5980, 853, 15284, 1512, 17349, 19069, 8807, 17625, 8410, 9640, 6462, 2487, 7111, 5678, 5433, 4432, 1309, 7152, 16496, 12671, 5464, 11442, 1298, 12490, 20321, 8129, 15534, 17290, 15049, 4055, 12697, 9548, 4577, 10025, 9747, 15109, 13031, 14586, 17472, 14176, 1404, 9858, 12893, 13153, 5639, 1778, 13316, 294, 13601, 15562, 10857, 18732, 16806, 893, 12472, 13954, 5613, 2968, 9097, 9183, 5, 18123, 10921, 6340, 10481, 10322, 8536, 14972, 3245, 13014, 11783, 10557, 12300, 13141, 9168, 9967, 1773, 11948, 5499, 6717, 9385, 12936, 1981, 12293, 8495, 15067, 19558, 2296, 15540, 9887, 19108, 8534, 13380, 5382, 8465, 5981, 12899, 8699, 829, 5641, 11242, 7022, 6649, 19177, 16938, 15460, 15134, 19541, 14305, 10910, 7915, 13352, 19091, 3464, 5532, 6281, 1223, 19044, 16871, 13810, 10733, 13736, 20399, 6615, 8516, 4819, 3836, 15631, 1242, 6744, 5786, 14079, 415, 7028, 13934, 19000, 15862, 18502, 10064, 9378, 17421, 4442, 4959, 17577, 10212, 18750, 9581, 1852, 16172, 16581, 9214, 14475, 10953, 777, 16310, 8414, 1510, 5462, 538, 17094, 12286, 13839, 11604, 5630, 11122, 1772, 13851, 19171, 1287, 12944, 20310, 17256, 11890, 10485, 6293, 2845, 1381, 2180, 5703, 730, 19347, 16477, 83, 19292, 8866, 2189, 17936, 1669, 7793, 16300, 19059, 6584, 12820, 301, 10411, 10642, 1975, 5517, 14578, 7189, 16126, 10668, 4595, 18973, 10563, 5272, 12220, 6904, 5642, 16711, 16400, 9508, 502, 19530, 2769, 19894, 8663, 16217, 15961, 5975, 15125, 4542, 3880, 5089, 6058, 6986, 13888, 17908, 8348, 14400, 18523, 1079, 15394, 11546, 2991, 473, 7051, 17574, 6009, 12655, 6092, 4748, 2196, 8834, 257, 12058, 5570, 3058, 18966, 8343, 12785, 8117, 15024, 1056, 10216, 19448, 10828, 7908, 15241, 17157, 242, 4990, 8535, 5698, 12166, 20523, 10791, 10107, 20404, 5838, 18437, 18624, 9910, 16413, 19445, 3150, 13449, 11871, 6430, 4770, 6873, 10470, 2474, 12280, 18214, 10017, 759, 13178, 14610, 6097, 14299, 6843, 2425, 12907, 2464, 11477, 20369, 4025, 18174, 16577, 656, 14728, 3138, 11367, 9898, 10786, 323, 4580, 6793, 15557, 15825, 19008, 1444, 453, 8076, 2692, 19732, 16103, 2016, 16794, 12112, 9401, 12506, 17868, 8320, 1499, 15617, 15501, 6362, 12175, 9933, 19105, 14151, 714, 6874, 4511, 13566, 17603, 11240, 3426, 4886, 7992, 3045, 15955, 18725, 10701, 12838, 10342, 7616, 2012, 5412, 8902, 5745, 12702, 5696, 3748, 2995, 18520, 12121, 5384, 14663, 2823, 11091, 15512, 2475, 2063, 4701, 5979, 14171, 2883, 7183, 9776, 13448, 12926, 8607, 671, 14922, 19947, 17278, 493, 12728, 19760, 349, 18753, 1054, 4738, 2083, 7928, 20529, 5550, 13230, 16409, 1736, 14787, 1456, 7824, 7994, 16755, 10303, 9950, 11799, 11378, 12599, 17701, 4168, 857, 10229, 14942, 16504, 8510, 4181, 18805, 12093, 6465, 14329, 13699, 14397, 8073, 10004, 17445, 7347, 5280, 10019, 4712, 9252, 683, 8489, 16204, 19017, 10023, 2577, 2536, 8437, 9978, 9041, 12872, 1267, 2247, 7528, 19911, 12193, 1349, 5473, 6016, 10058, 10715, 3241, 956, 58, 9791, 8566, 12225, 15073, 4769, 852, 7849, 5970, 6802, 15183, 8038, 20377, 8801, 2105, 10621, 9870, 16363, 4515, 5159, 14768, 11544, 19216, 7525, 12862, 4737, 6228, 14015, 13612, 2469, 16568, 14078, 17618, 13297, 12141, 11888, 2010, 9836, 9089, 13043, 17522, 1044, 10546, 13310, 7787, 15437, 6776, 8827, 5474, 1636, 4537, 8740, 8780, 998, 4484, 15355, 17176, 19003, 18594, 975, 19675, 19095, 14392, 18208, 504, 9827, 549, 5689, 8194, 15232, 6356, 10427, 4232, 17191, 19151, 15320, 12726, 11862, 1136, 4482, 9254, 4752, 8755, 20478, 15271, 1166, 19907, 11414, 1794, 12984, 10567, 5415, 1953, 7570, 18227, 18972, 5027, 8505, 8672, 8098, 188, 10674, 15221, 20637, 15360, 4579, 14913, 15258, 16589, 369, 10896, 89, 7563, 19734, 19527, 7946, 19698, 1350, 15034, 6088, 14977, 14780, 2979, 19471, 17306, 11637, 8800, 12261, 8612, 6968, 3955, 16625, 11490, 19831, 5277, 16393, 2607, 3910, 16464, 16139, 4534, 1272, 11906, 19590, 12854, 9861, 4988, 18329, 1165, 16302, 2727, 5763, 12408, 19867, 11409, 16511, 6242, 14285, 15560, 10502, 5777, 12529, 19083, 9974, 17149, 11895, 2149, 13181, 7290, 2122, 5894, 17808, 17412, 16578, 8934, 4407, 14214, 11963, 18455, 15498, 15128, 14618, 7789, 18458, 5251, 5948, 15044, 11748, 9934, 19756, 707, 4551, 13205, 12606, 4750, 11015, 2051, 17843, 5247, 12183, 2782, 8451, 10626, 298, 2347, 9788, 1271, 12815, 16283, 14372, 10131, 17820, 18767, 17090, 19339, 18669, 16830, 18273, 3263, 14002, 9730, 12825, 13952, 1837, 7115, 2697, 12004, 2908, 49, 5922, 9578, 1599, 327, 11602, 17749, 11247, 2352, 18684, 15471, 99, 2008, 9129, 15992, 19818, 19466, 1958, 9810, 14451, 10520, 1156, 2825, 4980, 14053, 3462, 14144, 2592, 12124, 15799, 4948, 18064, 534, 1564, 20544, 4399, 18149, 13090, 738, 16433, 769, 6043, 8480, 16556, 11054, 18667, 16245, 12601, 13937, 17942, 4902, 6893, 18839, 9263, 916, 19182, 2716, 3200, 8236, 15029, 16100, 15351, 1190, 6908, 16391, 5182, 19781, 4744, 7796, 6048, 8005, 10072, 13274, 16457, 1799, 10370, 11280, 19026, 14667, 11207, 14341, 9159, 15272, 17653, 4057, 9439, 9907, 8972, 6571, 14726, 17115, 9383, 7366, 1991, 18407, 10003, 15666, 1380, 13899, 1706, 12137, 10008, 4955, 13443, 18895, 17696, 11588, 12693, 18936, 15008, 10006, 1200, 20430, 17534, 6774, 14249, 7604, 1388, 15700, 11020, 7950, 6268, 9447, 414, 2301, 16287, 11118, 8821, 12242, 11523, 5375, 11923, 3004, 11514, 15830, 12267, 6711, 15191, 19245, 4497, 1417, 2923, 2980, 6032, 1774, 19511, 18869, 20507, 5218, 2955, 9037, 4132, 5792, 7845, 6415, 1477, 1519, 10387, 9377, 18759, 14472, 16919, 7791, 16317, 11568, 5031, 17869, 119, 8569, 19710, 11950, 2807, 9066, 8841, 15238, 8515, 11265, 5632, 19414, 7577, 4805, 19136, 3717, 4841, 19899, 20622, 10278, 6422, 6570, 8893, 639, 3046, 4467, 887, 10335, 16003, 14596, 12775, 16942, 7866, 3560, 11777, 4327, 15571, 13562, 3485, 13895, 17654, 16792, 11579, 2146, 862, 16210, 821, 5300, 16271, 4574, 8252, 2617, 11104, 19280, 5839, 16743, 10164, 1397, 17626, 7185, 3767, 7064, 16153, 17416, 18713, 18880, 17877, 52, 3389, 10358, 6577, 14723, 7375, 9699, 11907, 2849, 5199, 20368, 2223, 19224, 18758, 13452, 3785, 3072, 6506, 7009, 8433, 3518, 8629, 6073, 16976, 13197, 3770, 1343, 5687, 7844, 16870, 4736, 8773, 4274, 18608, 12547, 4845, 17118, 19954, 2307, 19949, 9309, 15387, 9989, 6197, 10600, 15110, 15322, 565, 10770, 11493, 7208, 12592, 17242, 16524, 4283, 1786, 9464, 2843, 15509, 13504, 3917, 7381, 11770, 13189, 1530, 19559, 3703, 11107, 12042, 6171, 19085, 1928, 8635, 14607, 8395, 

In [33]:
train_concate = train[train.Patient_ID.isin(td_num)]

train_concate.to_csv("../Data/train_concate.csv",sep = '|')

In [ ]:
train_concate = pd.read_csv("../Data/train_concate.csv", sep = '|')

,Unnamed: 0.1,Unnamed: 0,Hour,HR,O2Sat,Temp,SBP,MAP,DBP,Resp,...,Fibrinogen,Platelets,Age,Gender,Unit1,Unit2,HospAdmTime,ICULOS,SepsisLabel,Patient_ID
0,43,0,0,75.5,95.0,37.44,135.0,88.33,NaN,24.5,...,NaN,NaN,46.32,1,NaN,NaN,-0.04,4,0,16153
1,44,1,1,84.0,95.0,37.22,124.0,81.33,NaN,22.0,...,NaN,NaN,46.32,1,NaN,NaN,-0.04,5,0,16153
2,45,2,2,89.0,96.0,NaN,132.0,84.00,NaN,24.0,...,NaN,NaN,46.32,1,NaN,NaN,-0.04,6,0,16153
3,46,3,3,85.0,95.0,NaN,140.0,87.33,NaN,22.0,...,NaN,NaN,46.32,1,NaN,NaN,-0.04,7,0,16153
4,47,4,4,83.0,94.0,NaN,108.0,76.67,NaN,21.0,...,NaN,260.0,46.32,1,NaN,NaN,-0.04,8,0,16153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
552834,790162,27,27,92.0,98.0,NaN,93.0,70.00,56.0,15.0,...,NaN,NaN,61.31,0,NaN,NaN,-8.17,33,0,11204
552835,790163,28,28,89.0,98.0,NaN,90.0,69.00,55.0,14.0,...,NaN,NaN,61.31,0,NaN,NaN,-8.17,34,0,11204
552836,790164,29,29,94.0,98.0,35.83,92.0,69.00,55.0,14.0,...,NaN,NaN,61.31,0,NaN,NaN,-8.17,35,0,11204
552837,790165,30,30,98.0,97.0,NaN,94.0,70.00,55.0,13.0,...,NaN,NaN,61.31,0,NaN,NaN,-8.17,36,0,11204
552838,790166,31,31,102.0,97.0,NaN,122.0,96.00,77.0,20.0,...,NaN,761.0,61.31,0,NaN,NaN,-8.17,37,0,11204

In [35]:
train_concate.shape

(552839, 44)

In [37]:
val_num = []
for i in range(len(val_id)):
    val_num.append(val_id[i][1:7])
    
val_concate = train[train.Patient_ID.isin(val_num)]

In [38]:
val_concate.to_csv('../Data/val_concate.csv', sep = '|')

In [ ]:
pd.read_csv('../Data/val_concate.csv', sep = '|')

,HR,O2Sat,Temp,SBP,MAP,DBP,Resp,EtCO2,BaseExcess,HCO3,...,Fibrinogen,Platelets,Age,Gender,Unit1,Unit2,HospAdmTime,ICULOS,SepsisLabel,patient_id
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,75.91,0,0.0,1.0,-98.60,1,0,2
1,61.0,99.0,36.44,124.0,65.0,43.0,17.5,NaN,NaN,NaN,...,NaN,NaN,75.91,0,0.0,1.0,-98.60,2,0,2
2,64.0,98.0,NaN,125.0,64.0,41.0,27.0,NaN,NaN,NaN,...,NaN,NaN,75.91,0,0.0,1.0,-98.60,3,0,2
3,56.0,100.0,NaN,123.0,65.0,41.0,9.0,NaN,NaN,NaN,...,NaN,NaN,75.91,0,0.0,1.0,-98.60,4,0,2
4,66.0,99.0,NaN,120.0,67.0,43.0,23.0,NaN,NaN,NaN,...,NaN,NaN,75.91,0,0.0,1.0,-98.60,5,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118868,55.0,96.0,37.67,100.0,77.0,NaN,18.0,NaN,NaN,NaN,...,NaN,NaN,38.02,1,NaN,NaN,-0.03,11,0,20630
118869,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,38.02,1,NaN,NaN,-0.03,12,0,20630
118870,60.0,97.0,NaN,100.0,83.0,NaN,19.0,NaN,NaN,NaN,...,NaN,NaN,38.02,1,NaN,NaN,-0.03,13,0,20630
118871,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,38.02,1,NaN,NaN,-0.03,14,0,20630
118872,69.0,96.0,38.00,105.0,73.0,NaN,20.0,NaN,NaN,NaN,...,NaN,NaN,38.02,1,NaN,NaN,-0.03,15,0,20630

In [40]:
test_num = []
for i in range(len(test_id)):
    test_num.append(list(test_id)[i][1:7])
    
test_concate = train[train.Patient_ID.isin(test_num)]

In [41]:
test_concate.to_csv('../Data/test_concate.csv', sep = '|', index = False)

In [ ]:
pd.read_csv('../Data/test_concate.csv', sep = '|')

,HR,O2Sat,Temp,SBP,MAP,DBP,Resp,EtCO2,BaseExcess,HCO3,...,Fibrinogen,Platelets,Age,Gender,Unit1,Unit2,HospAdmTime,ICULOS,SepsisLabel,patient_id
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,45.76,0,1.0,0.0,-0.03,1,0,17
1,79.0,98.0,NaN,134.0,81.33,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,45.76,0,1.0,0.0,-0.03,2,0,17
2,81.0,98.0,NaN,121.0,80.33,NaN,16.0,NaN,NaN,NaN,...,NaN,NaN,45.76,0,1.0,0.0,-0.03,3,0,17
3,88.0,100.0,NaN,131.0,77.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,45.76,0,1.0,0.0,-0.03,4,0,17
4,86.0,100.0,NaN,143.0,89.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,45.76,0,1.0,0.0,-0.03,5,0,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118234,83.0,94.0,37.5,149.0,83.00,55.0,17.0,NaN,NaN,NaN,...,NaN,NaN,74.53,0,0.0,1.0,-59.09,23,0,20640
118235,74.0,93.0,37.5,147.0,77.00,50.0,15.0,NaN,NaN,NaN,...,NaN,NaN,74.53,0,0.0,1.0,-59.09,24,0,20640
118236,74.0,95.0,37.5,138.0,74.00,52.0,15.0,NaN,NaN,NaN,...,NaN,NaN,74.53,0,0.0,1.0,-59.09,25,0,20640
118237,71.0,97.0,37.4,135.0,73.33,59.0,14.0,NaN,NaN,NaN,...,NaN,NaN,74.53,0,0.0,1.0,-59.09,26,0,20640
118238,73.0,98.0,NaN,140.0,78.00,NaN,21.0,NaN,NaN,NaN,...,NaN,NaN,74.53,0,0.0,1.0,-59.09,27,0,20640